// Real local Firestore transactions + existing exported payout refund handler.
// Explicit trusted handler contexts, not HTTP authentication/production proof.
const assert=require('node:assert/strict');
for(const key of ['FIRESTORE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST','FIREBASE_STORAGE_EMULATOR_HOST'])if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env[key]||''))throw Error('Loopback emulators required');
const P=process.env.GCLOUD_PROJECT;if(!/^demo-/.test(P||''))throw Error('Demo project required');process.env.STORAGE_EMULATOR_HOST='http://'+process.env.FIREBASE_STORAGE_EMULATOR_HOST;
const admin=require('firebase-admin'),app=admin.initializeApp({projectId:P,storageBucket:P+'.appspot.com'}),db=app.firestore(),auth=app.auth();
const remove=require('../lib/customer/deleteUserData').deleteUserData,refund=require('../lib/customer/reviewEmployeePayout').rejectEmployeePayout;
let seq=0,passed=0,failed=0;
async function fixture(){const uid='wallet-race-'+(++seq);await auth.createUser({uid});await db.doc('users/'+uid).set({name:'Private fixture'});await db.doc('wallets/'+uid).set({balance:0,userId:uid});return {uid,at:Math.floor(Date.now()/1000)};}
const call=u=>remove.run({expectedOwnerId:u.uid},{auth:{uid:u.uid,token:{auth_time:u.at}}});
async function creditRefund(u){const r=await refund.run({auth:{uid:'demo-race-admin',token:{admin:true}},data:{payoutId:u.uid,reason:'Fixture reversal'}});assert.equal(r.success,true);assert.equal(r.amountReturned,9);}
async function payout(u){await db.doc('employee_payouts/'+u.uid).set({employeeId:u.uid,status:'requested',amount:9});}
async function preserved(u,balance){assert.equal((await db.doc('wallets/'+u.uid).get()).data().balance,balance);assert.equal((await db.doc('users/'+u.uid).get()).exists,true);assert.equal((await auth.getUser(u.uid)).uid,u.uid);}
async function afterInitialRead(u,fn,body){const proto=Object.getPrototypeOf(db.doc('wallets/'+u.uid)),original=proto.get;let fired=false;proto.get=async function(...args){const s=await original.apply(this,args);if(this.path==='wallets/'+u.uid&&!fired){fired=true;await fn();}return s;};try{await body();assert.equal(fired,true);}finally{proto.get=original;}}
async function beforeFinalRead(u,fn,body){const original=db.runTransaction;let fired=false;db.runTransaction=function(update,options){return original.call(db,async tx=>{const get=tx.get.bind(tx);tx.get=async function(ref,...args){if(ref.path==='wallets/'+u.uid&&!fired){fired=true;await fn();}return get(ref,...args);};return update(tx);},options);};try{await body();assert.equal(fired,true);}finally{db.runTransaction=original;}}
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function run(){
 await auth.createUser({uid:'demo-race-admin'});await db.doc('users/demo-race-admin').set({role:'admin'});
 await check('actual rejected payout refund after initial zero snapshot remains spendable',async()=>{const u=await fixture();await payout(u);await afterInitialRead(u,()=>creditRefund(u),async()=>{let error;try{await call(u);}catch(e){error=e;}if(!error){const walletPresent=(await db.doc('wallets/'+u.uid).get()).exists;let authPresent=true;try{await auth.getUser(u.uid);}catch(e){if(e.code==='auth/user-not-found')authPresent=false;else throw e;}const refundRows=(await db.collection('wallet_transactions').where('userId','==',u.uid).get()).size;console.log('OBSERVED unsafe deletion after actual refund: walletPresent='+walletPresent+' authPresent='+authPresent+' refundRows='+refundRows);}assert.equal(error?.code,'failed-precondition');});await preserved(u,9);assert.equal((await db.doc('employee_payouts/'+u.uid).get()).data().status,'rejected');const rows=await db.collection('wallet_transactions').where('userId','==',u.uid).get();assert.equal(rows.size,1);assert.equal(rows.docs[0].data().amount,9);assert.equal(rows.docs[0].data().balanceAfter,9);});
 for(const value of [-1,'invalid',null])await check('changed wallet '+String(value)+' after initial snapshot refuses',async()=>{const u=await fixture();await afterInitialRead(u,()=>db.doc('wallets/'+u.uid).update({balance:value}),async()=>{await assert.rejects(()=>call(u),e=>e.code==='failed-precondition');});await preserved(u,value);});
 await check('real refund arriving at final transaction boundary refuses',async()=>{const u=await fixture();await beforeFinalRead(u,async()=>{await payout(u);await creditRefund(u);},async()=>{await assert.rejects(()=>call(u),e=>e.code==='failed-precondition');});await preserved(u,9);assert.equal((await db.doc('employee_payouts/'+u.uid).get()).data().status,'rejected');});
 await check('new legacy wallet credit arriving before final read survives',async()=>{const u=await fixture();await db.doc('wallets/'+u.uid).delete();await beforeFinalRead(u,()=>db.doc('wallets/'+u.uid).set({balance:9,userId:u.uid}),async()=>{await assert.rejects(()=>call(u),e=>e.code==='failed-precondition');});await preserved(u,9);});
 await check('uncontested zero wallet and profile deletion still completes',async()=>{const u=await fixture();assert.equal((await call(u)).success,true);assert.equal((await db.doc('wallets/'+u.uid).get()).exists,false);assert.equal((await db.doc('users/'+u.uid).get()).exists,false);await assert.rejects(()=>auth.getUser(u.uid),e=>e.code==='auth/user-not-found');});
 await check('uncontested missing wallet deletion still completes',async()=>{const u=await fixture();await db.doc('wallets/'+u.uid).delete();assert.equal((await call(u)).success,true);assert.equal((await db.doc('users/'+u.uid).get()).exists,false);await assert.rejects(()=>auth.getUser(u.uid),e=>e.code==='auth/user-not-found');});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Fixture failure: '+e.name+' '+e.message);process.exitCode=1;}).finally(()=>app.delete());
