// Real dispatch/accept cores and callable. Demo data; no users have push tokens.
const assert=require('node:assert/strict');
if(!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Loopback emulator required');
process.env.GCLOUD_PROJECT='demo-foundation-dispatch-cash';
const admin=require('firebase-admin');admin.initializeApp({projectId:process.env.GCLOUD_PROJECT});const db=admin.firestore();
const {Timestamp}=require('firebase-admin/firestore'),fft=require('firebase-functions-test')({projectId:process.env.GCLOUD_PROJECT});
const D=require('../lib/delivery/dispatch'), C=require('../lib/delivery/dispatchCallables'), M=require('../lib/delivery/riderMoney');
const accept=fft.wrap(C.acceptDeliveryOffer),NOW=Date.now(),STORE={lat:9.9252,lng:78.1198};
let seq=0,passed=0,failed=0;const riders=[];
async function scenario(label,fn){const start=riders.length;try{await db.doc('settings/rider_pay').set({codCashLimit:2000});await fn();passed++;console.log(`PASS ${label}`);}catch(e){failed++;console.log(`FAIL ${label}: ${e.message}`);}finally{const b=db.batch();for(const id of riders.slice(start))b.update(db.doc(`delivery_partners/${id}`),{isOnline:false});await b.commit();}}
const get=async p=>(await db.doc(p).get()).data();
async function fixture(fields={cashHeld:0},total=100,paymentMethod='cod'){
 const id=`fixture_cash_${++seq}`;riders.push(id);
 await db.doc(`delivery_partners/${id}`).set({status:'approved',isOnline:true,currentLat:STORE.lat,currentLng:STORE.lng,lastLocationUpdate:Timestamp.fromMillis(NOW)});
 if(fields!==null)await db.doc(`rider_accounts/${id}`).set(fields);
 await db.doc(`orders/${id}`).set({userId:'fixture_customer',sellerId:'fixture_seller',orderStatus:'ready_for_pickup',status:'ready_for_pickup',paymentMethod,total,pickupLat:STORE.lat,pickupLng:STORE.lng,deliveryAddress:{latitude:STORE.lat+.01,longitude:STORE.lng}});
 return id;
}
async function offer(id){await db.doc(`delivery_requests/${id}_${id}`).set({orderId:id,riderId:id,status:'offered',expiresAt:Timestamp.fromMillis(NOW+30000)});}
const start=id=>get(`orders/${id}`).then(o=>D.startDispatch(db,id,o,NOW));
async function refusedWithoutAssignment(id,reason){await offer(id);await assert.rejects(accept({data:{orderId:id},auth:{uid:id,token:{}}}),e=>e.details?.reason===reason);assert.equal((await get(`orders/${id}`)).deliveryPartnerId,undefined);assert.equal((await get(`delivery_partners/${id}`)).currentOrderId,undefined);assert.equal((await get(`delivery_requests/${id}_${id}`)).status,'offered');}
(async()=>{
 await scenario('authoritative over-limit paise prevents offer',async()=>{const id=await fixture({cashHeld:0,cashHeldPaise:200000});assert.equal((await start(id)).offered.includes(id),false);});
 await scenario('authoritative over-limit paise prevents acceptance',async()=>{const id=await fixture({cashHeld:0,cashHeldPaise:200000});await refusedWithoutAssignment(id,'cash_limit');});
 await scenario('authoritative under-limit paise beats stale high rupees',async()=>{const id=await fixture({cashHeld:9000,cashHeldPaise:199999});assert.equal((await start(id)).offered.includes(id),true);assert.equal((await C.acceptOfferCore(db,id,id,NOW)).kind,'accepted');});
 const invalid=[{cashHeld:-1e-12},{cashHeld:'0'},{cashHeld:NaN},{cashHeld:Infinity},{cashHeld:-1},{cashHeld:1.001},{cashHeld:0,cashHeldPaise:null},{cashHeld:0,cashHeldPaise:.5},{cashHeldPaise:-1},{cashHeldPaise:Number.MAX_SAFE_INTEGER+1}];
 for(const fields of invalid){await scenario(`corrupt balance excludes COD offer ${JSON.stringify(fields)}`,async()=>{const id=await fixture(fields);assert.equal((await start(id)).offered.includes(id),false);});await scenario(`corrupt balance refuses COD accept ${JSON.stringify(fields)}`,async()=>{const id=await fixture(fields);await refusedWithoutAssignment(id,'bad_money_state');});}
 await scenario('prepaid order remains eligible with malformed cash account',async()=>{const id=await fixture({cashHeldPaise:null},100,'razorpay');assert.equal((await start(id)).offered.includes(id),true);assert.equal((await C.acceptOfferCore(db,id,id,NOW)).kind,'accepted');});
 await scenario('missing legacy account means zero cash',async()=>{const id=await fixture(null);assert.equal((await start(id)).offered.includes(id),true);assert.equal((await C.acceptOfferCore(db,id,id,NOW)).kind,'accepted');});
 await scenario('zero cash threshold blocks missing account',async()=>{const id=await fixture(null);await db.doc('settings/rider_pay').set({codCashLimit:0});assert.equal((await start(id)).offered.includes(id),false);await refusedWithoutAssignment(id,'cash_limit');});
 await scenario('valid legacy floating balance remains eligible',async()=>{const id=await fixture({cashHeld:.1+.2});assert.equal((await start(id)).offered.includes(id),true);assert.equal((await C.acceptOfferCore(db,id,id,NOW)).kind,'accepted');});
 await scenario('balance rechecked after offer and deposit restores eligibility',async()=>{const id=await fixture({cashHeldPaise:199999});assert.equal((await start(id)).offered.includes(id),true);await db.doc(`rider_accounts/${id}`).update({cashHeldPaise:200000,cashHeld:0});await assert.rejects(accept({data:{orderId:id},auth:{uid:id,token:{}}}),e=>e.details?.reason==='cash_limit');await M.recordCashDepositCore(db,'fixture_admin',id,.01,'FIXTURE_RECEIPT',NOW,'fixture_cash_deposit');assert.equal((await C.acceptOfferCore(db,id,id,NOW)).kind,'accepted');});
 for(const total of ['100',NaN,Infinity,-1,-1e-12,1.001]){await scenario(`malformed COD total no offer ${String(total)}`,async()=>{const id=await fixture({cashHeld:0},total);assert.deepEqual((await start(id)).offered,[]);assert.equal((await get(`delivery_dispatch/${id}`)).needsAdmin,true);});await scenario(`malformed COD total no accept ${String(total)}`,async()=>{const id=await fixture({cashHeld:0},total);await refusedWithoutAssignment(id,'bad_money_state');});}
 await scenario('zero-total COD has no cash liability',async()=>{const id=await fixture({cashHeldPaise:null},0);assert.equal((await start(id)).offered.includes(id),true);assert.equal((await C.acceptOfferCore(db,id,id,NOW)).kind,'accepted');});
 await scenario('corrupt account does not suppress valid riders',async()=>{const bad=await fixture({cashHeldPaise:null}),good=await fixture({cashHeldPaise:0});const r=await start(good);assert.deepEqual(r.offered,[good]);assert.equal(r.offered.includes(bad),false);});
 await scenario('existing accepted retry succeeds after later cash corruption',async()=>{const id=await fixture();await offer(id);await C.acceptOfferCore(db,id,id,NOW);await db.doc(`rider_accounts/${id}`).set({cashHeldPaise:null});assert.equal((await C.acceptOfferCore(db,id,id,NOW)).alreadyAccepted,true);assert.equal((await db.collection('orders').where('deliveryPartnerId','==',id).get()).size,1);});
 await scenario('missing COD total produces no offers',async()=>{const id=await fixture();await db.doc(`orders/${id}`).update({total:admin.firestore.FieldValue.delete()});assert.deepEqual((await start(id)).offered,[]);assert.equal((await get(`delivery_dispatch/${id}`)).needsAdmin,true);});
 await scenario('missing COD total refuses acceptance',async()=>{const id=await fixture();await db.doc(`orders/${id}`).update({total:admin.firestore.FieldValue.delete()});await refusedWithoutAssignment(id,'bad_money_state');});
 await scenario('reviewed COD total resumes dispatch without a stuck lease',async()=>{const id=await fixture({cashHeldPaise:0},'invalid');await start(id);const first=await get(`delivery_dispatch/${id}`);assert.equal(first.cashReviewReason,'invalid_cod_total');assert.equal(first.leaseUntil.toMillis(),0);await db.doc(`orders/${id}`).update({total:100});const r=await D.runNextWave(db,id,NOW+120001);assert.deepEqual(r.offered,[id]);assert.equal((await get(`delivery_dispatch/${id}`)).cashReviewReason,undefined);});
 await scenario('cash reads exclude far stale busy and unrelated accounts',async()=>{const good=await fixture(),far=await fixture({cashHeldPaise:null}),stale=await fixture({cashHeldPaise:null}),busy=await fixture({cashHeldPaise:null});await db.doc(`delivery_partners/${far}`).update({currentLat:STORE.lat+1});await db.doc(`delivery_partners/${stale}`).update({lastLocationUpdate:Timestamp.fromMillis(NOW-600001)});await db.doc('orders/fixture_cash_busy').set({orderStatus:'delivery_accepted',status:'delivery_accepted',deliveryPartnerId:busy});await db.doc('rider_accounts/fixture_unrelated_cash').set({cashHeldPaise:null});const original=db.getAll;const reads=[];db.getAll=function(...refs){reads.push(...refs.filter(r=>r.path?.startsWith('rider_accounts/')).map(r=>r.id));return original.apply(this,refs);};try{assert.deepEqual((await start(good)).offered,[good]);assert.deepEqual(reads,[good]);}finally{db.getAll=original;}});
 await scenario('120 eligible accounts use bounded direct batches',async()=>{const ids=[];for(let i=0;i<120;i++)ids.push(await fixture({cashHeldPaise:0}));const original=db.getAll,batches=[];db.getAll=function(...refs){const accounts=refs.filter(r=>r.path?.startsWith('rider_accounts/'));if(accounts.length)batches.push(accounts.length);return original.apply(this,refs);};try{const r=await start(ids[0]);assert.equal(r.offered.length,3);assert.deepEqual(batches,[100,20]);}finally{db.getAll=original;}});
 console.log(`RESULT ${passed} passed; ${failed} failed`);fft.cleanup();await db.terminate();if(failed)process.exitCode=1;
})().catch(async e=>{console.error(e.stack);fft.cleanup();await db.terminate();process.exitCode=1;});
