// Actual bounded scheduled handler, ledger transactions and client rules.
// Strict demo services only; no production, payment providers or device IO.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const k of ['FIRESTORE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST','FIREBASE_STORAGE_EMULATOR_HOST'])if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env[k]||''))throw Error('Loopback required');
const P=process.env.GCLOUD_PROJECT;if(!/^demo-/.test(P||''))throw Error('Demo project required');process.env.STORAGE_EMULATOR_HOST='http://'+process.env.FIREBASE_STORAGE_EMULATOR_HOST;
const admin=require('firebase-admin'),app=admin.initializeApp({projectId:P,storageBucket:P+'.appspot.com'}),db=app.firestore();const run=require('../lib/customer/productCreditExpiry').expireProductCredits;
const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc,updateDoc,deleteDoc}=require('firebase/firestore');
const cursor=db.doc('product_credit_expiry_cursors/credits');let env,passed=0,failed=0;
async function batches(refs,del=false){for(let i=0;i<refs.length;i+=450){const b=db.batch();for(const x of refs.slice(i,i+450))del?b.delete(x):b.set(x.ref,x.data);await b.commit();}}
async function reset(){for(const c of ['product_credit_ledger','product_credit_balances','product_credit_expiry_cursors'])await batches((await db.collection(c).get()).docs.map(d=>d.ref),true);}
async function credit(id,uid,expiry=1){await db.doc('product_credit_ledger/'+id).set({customerId:uid,enrollmentId:'',type:'CREDIT',amount:1,expiresAt:admin.firestore.Timestamp.fromMillis(expiry),createdAt:admin.firestore.Timestamp.fromMillis(0)});}
async function tailFixture(){await reset();await batches(Array.from({length:500},(_,i)=>({ref:db.doc('product_credit_ledger/a_head_'+String(i).padStart(3,'0')),data:{customerId:'spent-head',enrollmentId:'',type:'CREDIT',amount:1,expiresAt:admin.firestore.Timestamp.fromMillis(1)}})));await db.doc('product_credit_ledger/spent_history').set({customerId:'spent-head',type:'REDEMPTION',amount:500,relatedEntryId:null});await db.doc('product_credit_balances/spent-head').set({available:0,onHold:0,pending:0,lifetimeEarned:500,lifetimeUsed:500,lifetimeExpired:0});await credit('z_tail','due-tail');await db.doc('product_credit_balances/due-tail').set({available:1,pending:0,onHold:0,lifetimeEarned:1,lifetimeUsed:0,lifetimeExpired:0});}
const sweep=()=>run.run({});async function available(uid){return (await db.doc('product_credit_balances/'+uid).get()).data().available;}
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function main(){
 env=await initializeTestEnvironment({projectId:P,firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(path.join(__dirname,'../../firestore.rules'),'utf8')}});
 await check('501st due credit advances past500 permanently skipped same-timestamp records',async()=>{await tailFixture();const a=await sweep(),b=await sweep(),n=await available('due-tail');if(n!==0)console.log('OBSERVED starvation: tailAvailable='+n+' firstProcessed='+a.processed+' secondProcessed='+b.processed);assert.equal(a.processed,500);assert.equal(a.truncated,true);assert.equal(b.processed,1);assert.equal(b.expired,1);assert.equal(n,0);assert.equal((await db.collection('product_credit_ledger').where('relatedEntryId','==','z_tail').where('type','==','EXPIRY').get()).size,1);const c=(await cursor.get()).data();assert.equal(c.version,2);assert.equal(c.lastExpiresAt,null);assert.equal(c.lastEntryId,null);const third=await sweep();assert.equal(third.expired,0);assert.equal(await available('due-tail'),0);});
 await check('new early record behindcheckpoint is revisited after cycle reset',async()=>{await tailFixture();await sweep();await credit('a_early_new','new-early');await db.doc('product_credit_balances/new-early').set({available:1});await sweep();assert.equal(await available('new-early'),1);await sweep();assert.equal(await available('new-early'),0);});
 await check('interrupted page resumes without duplicateexpiry or advancedcheckpoint',async()=>{await reset();for(let i=0;i<3;i++)await credit('credit_0'+i,'retry-owner');await db.doc('product_credit_balances/retry-owner').set({available:3});const original=db.runTransaction;let fired=false;db.runTransaction=function(fn,...args){return original.call(this,async tx=>{const get=tx.get.bind(tx);tx.get=async(ref,...rest)=>{if(!fired&&ref.path==='product_credit_ledger/credit_01'){fired=true;throw Error('Synthetic page interruption');}return get(ref,...rest);};return fn(tx);},...args);};try{await assert.rejects(()=>sweep());assert.equal(fired,true);}finally{db.runTransaction=original;}assert.equal((await cursor.get()).exists,false);await sweep();assert.equal(await available('retry-owner'),0);assert.equal((await db.collection('product_credit_ledger').where('type','==','EXPIRY').get()).size,3);await sweep();assert.equal((await db.collection('product_credit_ledger').where('type','==','EXPIRY').get()).size,3);});
 await check('older overlapping run cannot overwrite two newer checkpoint revisions',async()=>{await reset();await credit('overlap_credit','overlap-owner');await db.doc('product_credit_balances/overlap-owner').set({available:1});let enteredResolve,resumeResolve,held=false;const entered=new Promise(r=>enteredResolve=r),resume=new Promise(r=>resumeResolve=r),original=db.runTransaction;db.runTransaction=function(fn,...args){return original.call(this,async tx=>{const get=tx.get.bind(tx);tx.get=async(ref,...rest)=>{if(!held&&ref.path===cursor.path){held=true;enteredResolve();await resume;}return get(ref,...rest);};return fn(tx);},...args);};const first=sweep();try{await Promise.race([entered,new Promise((_,reject)=>setTimeout(()=>reject(Error('Checkpoint pause not reached')),5000))]);await sweep();await sweep();assert.equal((await cursor.get()).data().version,2);resumeResolve();await first;const v=(await cursor.get()).data().version;if(v!==2)console.log('OBSERVED checkpoint regression: expectedVersion=2 actualVersion='+v);assert.equal(v,2);assert.equal((await db.collection('product_credit_ledger').where('type','==','EXPIRY').get()).size,1);}finally{resumeResolve();await first.catch(()=>{});db.runTransaction=original;}});
 await check('empty sweep stores valid reset checkpoint',async()=>{await reset();const r=await sweep();assert.equal(r.processed,0);const c=(await cursor.get()).data();assert.equal(c.version,1);assert.equal(c.lastExpiresAt,null);assert.equal(c.lastEntryId,null);await sweep();assert.equal((await cursor.get()).data().version,2);});
 for(const bad of [{version:0,lastExpiresAt:null,lastEntryId:null},{version:-1,lastExpiresAt:null,lastEntryId:null},{version:1,lastExpiresAt:1,lastEntryId:'credit'},{version:1,lastExpiresAt:admin.firestore.Timestamp.fromMillis(1),lastEntryId:null},{version:1,lastExpiresAt:null,lastEntryId:'credit'}])await check('malformed cursor fails before moneywrites '+JSON.stringify({version:bad.version,timestampType:typeof bad.lastExpiresAt,id:bad.lastEntryId}),async()=>{await reset();await credit('valid_credit','cursor-owner');await db.doc('product_credit_balances/cursor-owner').set({available:1});await cursor.set(bad);await assert.rejects(()=>sweep());assert.equal(await available('cursor-owner'),1);assert.equal((await db.collection('product_credit_ledger').where('type','==','EXPIRY').get()).size,0);assert.deepEqual((await cursor.get()).data(),bad);});
 await reset();await cursor.set({version:1,lastExpiresAt:null,lastEntryId:null});await db.doc('product_credit_balances/owner').set({available:1});
 for(const [name,claims] of [['owner',{}],['foreign',{}],['admin',{admin:true}],['anonymous',null]])await check(name+' client cannot read-create-update-delete privatecursor',async()=>{const c=claims===null?env.unauthenticatedContext():env.authenticatedContext(name,claims),r=doc(c.firestore(),'product_credit_expiry_cursors/credits');await assertFails(getDoc(r));await assertFails(setDoc(doc(c.firestore(),'product_credit_expiry_cursors/new'),{version:1}));await assertFails(updateDoc(r,{version:2}));await assertFails(deleteDoc(r));});
 await check('owner retains legitimate creditbalance read',async()=>{await assertSucceeds(getDoc(doc(env.authenticatedContext('owner').firestore(),'product_credit_balances/owner')));});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
main().catch(e=>{console.error('Fixture failure: '+e.name+' '+e.message);process.exitCode=1;}).finally(async()=>{if(env)await env.cleanup();await app.delete();});
