// Real demo records/Auth deletion; contexts are explicit trusted-handler fixtures,
// not HTTP authentication proof (covered separately by FOUNDATION26).
const assert=require('node:assert/strict');
for(const key of ['FIRESTORE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST','FIREBASE_STORAGE_EMULATOR_HOST'])if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env[key]||''))throw Error('Loopback emulators required');
const P=process.env.GCLOUD_PROJECT;if(!/^demo-/.test(P||''))throw Error('Demo project required');
process.env.STORAGE_EMULATOR_HOST='http://'+process.env.FIREBASE_STORAGE_EMULATOR_HOST;
const admin=require('firebase-admin'),app=admin.initializeApp({projectId:P,storageBucket:P+'.appspot.com'}),db=app.firestore(),auth=app.auth();
const remove=require('../lib/customer/deleteUserData').deleteUserData;
let sequence=0,passed=0,failed=0;
async function fixture(){const uid='deletion-money-'+(++sequence);await auth.createUser({uid});await db.doc('users/'+uid).set({name:'Synthetic private fixture'});await db.doc('wallets/'+uid).set({userId:uid,balance:0});return {uid,authTime:Math.floor(Date.now()/1000)};}
const call=u=>remove.run({expectedOwnerId:u.uid},{auth:{uid:u.uid,token:{auth_time:u.authTime}}});
async function refuse(u,records=[]){const before=await Promise.all(['users/'+u.uid,'wallets/'+u.uid,...records].map(async p=>({p,data:(await db.doc(p).get()).data()})));await assert.rejects(()=>call(u),e=>e.code==='failed-precondition');for(const r of before)assert.deepEqual((await db.doc(r.p).get()).data(),r.data);assert.equal((await auth.getUser(u.uid)).uid,u.uid);assert.equal((await db.doc('account_deletion_audit/'+u.uid).get()).exists,false);}
async function allowed(u,records=[]){const before=await Promise.all(records.map(async p=>({p,data:(await db.doc(p).get()).data()})));assert.equal((await call(u)).success,true);assert.equal((await db.doc('users/'+u.uid).get()).exists,false);await assert.rejects(()=>auth.getUser(u.uid),e=>e.code==='auth/user-not-found');for(const r of before)assert.deepEqual((await db.doc(r.p).get()).data(),r.data);}
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function run(){
 for(const [name,value] of [['null',null],['string','invalid'],['numeric string','12'],['NaN',NaN],['infinity',Infinity],['object',{}],['array',[]],['boolean',false],['negative debt',-1],['sub-paise',0.001],['missing',undefined]])await check('wallet '+name+' refuses before mutation',async()=>{const u=await fixture();await db.doc('wallets/'+u.uid).set(value===undefined?{userId:u.uid}:{userId:u.uid,balance:value});await refuse(u);});
 for(const value of [0.01,5,12.34])await check('wallet valid positive '+value+' still refuses',async()=>{const u=await fixture();await db.doc('wallets/'+u.uid).update({balance:value});await refuse(u);});
 await check('missing wallet legacy no-account deletion remains usable',async()=>{const u=await fixture();await db.doc('wallets/'+u.uid).delete();await allowed(u);});
 await check('valid zero wallet deletes identity but retains ledger',async()=>{const u=await fixture(),p='wallet_transactions/'+u.uid;await db.doc(p).set({userId:u.uid,amount:9,type:'historic'});await allowed(u,[p]);});
 for(const value of [null,'invalid',0,-9,{},NaN])await check('pending seller amount '+String(value)+' cannot bypass refusal',async()=>{const u=await fixture(),p='seller_payouts/'+u.uid;await db.doc(p).set({sellerId:u.uid,status:'pending',netAmount:value});await refuse(u,[p]);});
 await check('negative seller row cannot cancel positive unsettled row',async()=>{const u=await fixture(),a='seller_payouts/'+u.uid+'a',b='seller_payouts/'+u.uid+'b';await db.doc(a).set({sellerId:u.uid,status:'pending',netAmount:10});await db.doc(b).set({sellerId:u.uid,status:'requested',netAmount:-10});await refuse(u,[a,b]);});
 for(const state of [null,'unknown','',42])await check('unknown seller state '+String(state)+' refuses',async()=>{const u=await fixture(),p='seller_payouts/'+u.uid;await db.doc(p).set({sellerId:u.uid,status:state,netAmount:0});await refuse(u,[p]);});
 for(const state of [null,'unknown','',42])await check('unknown employee state '+String(state)+' refuses',async()=>{const u=await fixture(),p='employee_payouts/'+u.uid;await db.doc(p).set({employeeId:u.uid,status:state,amount:0});await refuse(u,[p]);});
 for(const state of ['requested','pending'])await check('employee '+state+' remains blocked',async()=>{const u=await fixture(),p='employee_payouts/'+u.uid;await db.doc(p).set({employeeId:u.uid,status:state,amount:0});await refuse(u,[p]);});
 await check('paid seller and paid/rejected employee history retained unchanged',async()=>{const u=await fixture(),paths=['seller_payouts/'+u.uid,'employee_payouts/'+u.uid+'p','employee_payouts/'+u.uid+'r'];await db.doc(paths[0]).set({sellerId:u.uid,status:'paid',netAmount:8});await db.doc(paths[1]).set({employeeId:u.uid,status:'paid',amount:8});await db.doc(paths[2]).set({employeeId:u.uid,status:'rejected',amount:8});await allowed(u,paths);});
 for(const [name,data] of [['cash paise over stale zero rupees',{cashHeld:0,cashHeldPaise:1}],['earnings paise over stale zero rupees',{earningsUnsettled:0,earningsUnsettledPaise:1}],['cash malformed authoritative paise',{cashHeld:0,cashHeldPaise:'0'}],['earnings malformed authoritative paise',{earningsUnsettled:0,earningsUnsettledPaise:null}],['cash malformed legacy',{cashHeld:'invalid'}],['earnings malformed legacy',{earningsUnsettled:{}}],['cash negative',{cashHeld:-1}],['earnings negative debt',{earningsUnsettled:-1}],['fractional paise',{cashHeldPaise:0.5}],['sub-paise legacy',{cashHeld:0.001}],['NaN cash',{cashHeld:NaN}],['infinite earnings',{earningsUnsettled:Infinity}],['unsafe paise',{earningsUnsettledPaise:Number.MAX_SAFE_INTEGER+1}]])await check('rider '+name+' refuses',async()=>{const u=await fixture(),p='rider_accounts/'+u.uid;await db.doc(p).set(data);await refuse(u,[p]);});
 for(const state of ['pending','on_hold','unknown',null])await check('rider statement '+String(state)+' refuses',async()=>{const u=await fixture(),p='rider_payouts/'+u.uid;await db.doc(p).set({riderId:u.uid,status:state,amount:0});await refuse(u,[p]);});
 await check('authoritative zero paise overrides stale display and retains account/terminal statements',async()=>{const u=await fixture(),paths=['rider_accounts/'+u.uid,'rider_payouts/'+u.uid+'p','rider_payouts/'+u.uid+'z'];await db.doc(paths[0]).set({cashHeldPaise:0,earningsUnsettledPaise:0,cashHeld:9,earningsUnsettled:9});await db.doc(paths[1]).set({riderId:u.uid,status:'paid',amount:9});await db.doc(paths[2]).set({riderId:u.uid,status:'nothing_to_pay',amount:0});await allowed(u,paths);});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Fixture failed: '+e.name+' '+e.message);process.exitCode=1;}).finally(()=>app.delete());
