// Actual compiled cores and Admin SDK; loopback demo only, no bank transfer.
const assert=require('node:assert/strict');
if(!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Loopback emulator required');
process.env.GCLOUD_PROJECT='demo-bank-review-state';
const admin=require('firebase-admin');admin.initializeApp({projectId:process.env.GCLOUD_PROJECT});
const db=admin.firestore(),M=require('../lib/delivery/riderMoney');const NOW=Date.UTC(2026,9,5,2);let seq=0,passed=0,failed=0;
const old={accountHolderName:'Old Fixture',bankAccountNumber:'123456789012',ifscCode:'HDFC0001234',upiId:null};
const proposed={accountHolderName:'New Fixture',bankAccountNumber:'999988887777',ifscCode:'ICIC0001234',upiId:null};
async function scenario(label,fn){try{await fn();passed++;console.log('PASS '+label);}catch(e){failed++;console.log('FAIL '+label+': '+e.message);}}
async function fixture({marker='MATCH',account=true,partner=true,owner='MATCH',requestOwner='MATCH',requestDetails=proposed,currentDetails=old,status='pending'}={}){
 const rider=`review_rider_${++seq}`,request=`review_request_${seq}`,refs={request:db.doc(`rider_bank_change_requests/${request}`),account:db.doc(`rider_accounts/${rider}`),partner:db.doc(`delivery_partners/${rider}`),hold:db.doc(`rider_payouts/${rider}_hold`),noBank:db.doc(`rider_payouts/${rider}_no_bank`),manual:db.doc(`rider_payouts/${rider}_manual`),pending:db.doc(`rider_payouts/${rider}_pending`),foreign:db.doc(`rider_payouts/${rider}_foreign`)};
 const b=db.batch();b.set(refs.request,{riderId:requestOwner==='MATCH'?rider:requestOwner,...requestDetails,status});
 if(account){const data={cashHeldPaise:0,earningsUnsettledPaise:0};if(marker!=='ABSENT')data.bankChangePending=marker==='MATCH'?request:marker;if(owner!=='ABSENT')data.riderId=owner==='MATCH'?rider:owner;b.set(refs.account,data);}
 if(partner)b.set(refs.partner,{status:'approved',...currentDetails});
 for(const [key,holdReason] of [['hold','bank_change_pending'],['noBank','no_bank_details'],['manual','manual_review']])b.set(refs[key],{riderId:rider,status:'on_hold',holdReason,amountPaise:100});
 b.set(refs.pending,{riderId:rider,status:'pending',amountPaise:100});b.set(refs.foreign,{riderId:'other_rider',status:'on_hold',holdReason:'bank_change_pending',amountPaise:100});await b.commit();
 return {rider,request,refs};
}
async function snapshot(f){const rows=await Promise.all(Object.entries(f.refs).map(async([k,r])=>[k,(await r.get()).data()||null]));return Object.fromEntries(rows);}
function trace({rejectQuery=false}={}){const reads={docs:[],queries:0};const wrapped=new Proxy(db,{get(target,key){if(key==='runTransaction')return(callback,options)=>target.runTransaction(tx=>callback(new Proxy(tx,{get(t,k){if(k==='get')return(ref,...args)=>{if(ref.path)reads.docs.push(ref.path);else{reads.queries++;if(rejectQuery)throw Error('Synthetic held query refusal');}return t.get(ref,...args);};const v=t[k];return typeof v==='function'?v.bind(t):v;}})),options);const v=target[key];return typeof v==='function'?v.bind(target):v;}});return {db:wrapped,reads};}
async function refused(f,approve=true){const before=await snapshot(f),t=trace(),v=await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,approve,approve?null:'Fixture rejection',NOW);assert.deepEqual(v,{kind:'refused',reason:'bank_review_state'});assert.equal(t.reads.queries,0,'inconsistent review must not query held money');assert.deepEqual(await snapshot(f),before,'refusal must preserve every record');}
(async()=>{
 for(const approve of [true,false])await scenario(`another pending request cannot be cleared by ${approve?'approval':'rejection'}`,async()=>refused(await fixture({marker:'newer_pending_request'}),approve));
 await scenario('stale review cannot enable payment to the old requested destination',async()=>{const f=await fixture({marker:'newer_pending_request'});await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW);const v=await M.markPayoutPaidCore(db,'fixture_admin',f.refs.pending.id,'FIXTURE_UTR','bank',NOW+1);assert.deepEqual(v,{kind:'refused',reason:'bank_change_pending'});assert.equal((await f.refs.pending.get()).data().status,'pending');});
 for(const marker of ['ABSENT',null,'',17])for(const approve of [true,false])await scenario(`invalid marker ${String(marker)} refuses ${approve?'approve':'reject'} without effects`,async()=>refused(await fixture({marker}),approve));
 for(const missing of ['account','partner'])for(const approve of [true,false])await scenario(`missing ${missing} refuses ${approve?'approve':'reject'} without recreating it`,async()=>refused(await fixture({[missing]:false}),approve));
 for(const owner of ['other_rider',null,23])await scenario(`explicit account owner ${String(owner)} mismatch refuses review`,async()=>refused(await fixture({owner})));
 if(process.env.AGRIMORE_BANK_SKIP_BAD_IDS==='1')console.log('SKIP eight malformed owner controls for clean original SDK comparison');
 else for(const requestOwner of [null,23,'','a/b','.','..','__reserved__','x'.repeat(1501)])await scenario(`malformed request owner type/path case ${++seq} fails before linked reads`,async()=>{const f=await fixture({requestOwner});const before=await snapshot(f),t=trace();assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW),{kind:'refused',reason:'bank_review_state'});assert.deepEqual(t.reads.docs,[f.refs.request.path]);assert.equal(t.reads.queries,0);assert.deepEqual(await snapshot(f),before);});
 await scenario('malformed stored proposed destination cannot be approved',async()=>refused(await fixture({requestDetails:{upiId:'invalid payment address'}})));
 await scenario('valid approval releases only eligible own holds and preserves exact money',async()=>{const f=await fixture(),before=await snapshot(f);assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW),{kind:'approved',released:2});const after=await snapshot(f);assert.equal(after.account.bankChangePending,null);assert.equal(after.partner.bankAccountNumber,proposed.bankAccountNumber);assert.equal(after.request.status,'approved');for(const key of ['hold','noBank']){assert.equal(after[key].status,'pending');assert.equal(after[key].amountPaise,100);}for(const key of ['manual','pending','foreign'])assert.deepEqual(after[key],before[key]);});
 await scenario('valid rejection retains current destination and releases own eligible holds',async()=>{const f=await fixture(),before=await snapshot(f);assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,false,'Fixture rejection',NOW),{kind:'rejected',released:2});const after=await snapshot(f);assert.deepEqual(after.partner,before.partner);assert.equal(after.account.bankChangePending,null);assert.equal(after.request.rejectionReason,'Fixture rejection');});
 await scenario('rejection can safely discard invalid proposed details without installing them',async()=>{const f=await fixture({requestDetails:{upiId:'invalid'}}),before=await snapshot(f);assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,false,'Invalid proposed details',NOW),{kind:'rejected',released:2});assert.deepEqual((await snapshot(f)).partner,before.partner);});
 await scenario('rejection without a current destination releases no held payout',async()=>{const f=await fixture({currentDetails:{}});assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,false,'Fixture rejection',NOW),{kind:'rejected',released:0});assert.equal((await f.refs.hold.get()).data().status,'on_hold');});
 await scenario('legacy absent account owner remains valid with matching marker',async()=>{const f=await fixture({owner:'ABSENT'});assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW),{kind:'approved',released:2});});
 await scenario('historical not-pending result precedes inconsistent linked state',async()=>{const f=await fixture({status:'approved',account:false,partner:false}),before=await snapshot(f),t=trace();assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW),{kind:'refused',reason:'not_pending'});assert.deepEqual(t.reads.docs,[f.refs.request.path]);assert.equal(t.reads.queries,0);assert.deepEqual(await snapshot(f),before);});
 await scenario('review retry leaves economic records and destination unchanged',async()=>{const f=await fixture();await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW);const before=await snapshot(f);assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW+1),{kind:'refused',reason:'not_pending'});assert.deepEqual(await snapshot(f),before);});
 await scenario('approval/rejection race produces exactly one coherent transition',async()=>{const f=await fixture();const v=await Promise.all([M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW),M.reviewBankChangeCore(db,'fixture_admin',f.request,false,'Fixture rejection',NOW)]);assert.equal(v.filter(x=>x.kind==='refused'&&x.reason==='not_pending').length,1);const after=await snapshot(f);assert.equal(after.account.bankChangePending,null);assert.equal(after.request.status,v.find(x=>x.kind!=='refused').kind);assert.equal(after.partner.bankAccountNumber,after.request.status==='approved'?proposed.bankAccountNumber:old.bankAccountNumber);});
 await scenario('approval canonicalizes a valid legacy proposed destination',async()=>{const f=await fixture({requestDetails:{accountHolderName:' New Fixture ',bankAccountNumber:' 9999 8888 7777 ',ifscCode:'icic0001234',upiId:null}});assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW),{kind:'approved',released:2});const p=(await f.refs.partner.get()).data();assert.equal(p.bankAccountNumber,proposed.bankAccountNumber);assert.equal(p.ifscCode,proposed.ifscCode);assert.equal(p.accountHolderName,proposed.accountHolderName);});
 await scenario('UPI-only approval clears prior bank fields and releases own holds',async()=>{const f=await fixture({requestDetails:{upiId:'fixture@upi'}});assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',f.request,true,null,NOW),{kind:'approved',released:2});const p=(await f.refs.partner.get()).data();assert.equal(p.upiId,'fixture@upi');for(const key of ['bankAccountNumber','ifscCode','accountHolderName'])assert.equal(p[key],null);});
 await scenario('missing request remains not-found without any linked reads',async()=>{const t=trace();assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin','missing_fixture_request',true,null,NOW),{kind:'refused',reason:'not_found'});assert.deepEqual(t.reads.docs,['rider_bank_change_requests/missing_fixture_request']);assert.equal(t.reads.queries,0);});
 await scenario('missing rejection reason remains first refusal without any reads',async()=>{const t=trace();assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin','missing_fixture_request',false,null,NOW),{kind:'refused',reason:'reason_required'});assert.deepEqual(t.reads.docs,[]);assert.equal(t.reads.queries,0);});
 if(process.env.AGRIMORE_BANK_SKIP_BAD_IDS==='1')console.log('SKIP synthetic immediate query refusal on original parallel SDK reads');
 else await scenario('held query failure preserves all state and propagates',async()=>{const f=await fixture(),before=await snapshot(f),t=trace({rejectQuery:true});await assert.rejects(M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW),/Synthetic held query refusal/);assert.deepEqual(await snapshot(f),before);});
 console.log(`RESULT ${passed} passed; ${failed} failed`);await db.terminate();if(failed)process.exitCode=1;
})().catch(async e=>{console.error(e.stack);await db.terminate();process.exitCode=1;});
