// Actual fixed-fee and generic order handlers; no real payment provider calls.
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw new Error('Loopback emulator required');
process.env.GCLOUD_PROJECT='demo-agrimore-foundation';process.env.FUNCTIONS_EMULATOR='false';
process.env.RAZORPAY_KEY_ID='rzp_test_foundation6_fixture';process.env.RAZORPAY_KEY_SECRET='foundation6_fixture_not_a_provider_credential';process.env.AI_KEY_ENCRYPTION_SECRET=Buffer.alloc(32,6).toString('base64');
let seq=0,current,responseOverride={},calls=0,passed=0,failed=0,providerCapture;
const providerPath=require.resolve('razorpay');require.cache[providerPath]={id:providerPath,filename:providerPath,loaded:true,exports:class{constructor(){this.orders={create:async options=>{calls++;return {id:current.orderId,amount:options.amount,currency:options.currency,status:'created',receipt:options.receipt,...responseOverride};}};}}};
require('axios').get=async()=>{calls++;if(!providerCapture)throw new Error('Unexpected provider fetch blocked');return {data:{...providerCapture}};};
const admin=require('firebase-admin');admin.initializeApp({projectId:process.env.GCLOUD_PROJECT});const db=admin.firestore();
const fft=require('firebase-functions-test')({projectId:process.env.GCLOUD_PROJECT});
const {performOnboardingActivation}=require('../lib/employee/activationCore');
const associateCreate=fft.wrap(require('../lib/employee/createAssociateOnboardingPayment').createAssociateOnboardingPayment);
const sellerModule=require('../lib/seller/aiConnection');const sellerCreate=fft.wrap(sellerModule.createSellerAiActivationOrder),sellerConnect=fft.wrap(sellerModule.connectSellerAiProvider);
const payment=require('../lib/customer/payment'),genericCreate=fft.wrap(payment.createRazorpayOrder),genericVerify=fft.wrap(payment.verifyRazorpayPayment);
async function scenario(name,body){responseOverride={};providerCapture=undefined;await db.collection('settings').doc('associate_onboarding').set({isEnabled:true,feeAmount:500,currency:'INR',version:1});try{await body();passed++;console.log(`PASS ${name}`);}catch(e){failed++;console.log(`FAIL ${name}: ${e.message}`);}}
async function fixture(amount=500){const n=++seq,uid=`foundation6-owner-${n}`,paymentId=`pay_foundation6_${n}`,orderId=`order_foundation6_${n}`,auth={uid,token:{seller:true}};
 const employeeRef=db.collection('employees').doc(uid),paymentRef=db.collection('verified_payments').doc(paymentId);
 await employeeRef.set({userId:uid,status:'pending'});await paymentRef.set({paymentId,orderId,userId:uid,amount,currency:'INR',status:'captured',signatureVerified:true});current={uid,paymentId,orderId};return {uid,paymentId,orderId,auth,employeeRef,paymentRef};}
async function noActivation(f){assert.notEqual((await f.employeeRef.get()).data().onboardingPaidAt!==undefined,true);assert.equal((await db.collection('onboarding_events').where('uid','==',f.uid).get()).size,0);assert.equal((await f.paymentRef.get()).data().consumedByOnboardingFor,undefined);}
(async()=>{
 for(const fee of [500,599.99])for(const delta of [-0.01,0.01])await scenario(`associate rejects genuine one-paise ${delta<0?'under':'over'}payment for ${fee}`,async()=>{const f=await fixture(Math.round((fee+delta)*100)/100);await db.collection('settings').doc('associate_onboarding').update({feeAmount:fee});const r=await performOnboardingActivation({db,uid:f.uid,paymentId:f.paymentId,source:'client'});assert.equal(r.ok,false);assert.equal(r.failureCode,'payment_amount_mismatch');await noActivation(f);});
 await scenario('associate exact fractional-rupee fee activates without approval',async()=>{const f=await fixture(599.99);await db.collection('settings').doc('associate_onboarding').update({feeAmount:599.99});assert.equal((await performOnboardingActivation({db,uid:f.uid,paymentId:f.paymentId,source:'client'})).ok,true);assert.equal((await f.employeeRef.get()).data().status,'pending');});
 for(const source of ['client','webhook','reconciler'])await scenario(`refunded associate cannot reactivate from ${source}`,async()=>{const f=await fixture();await f.employeeRef.update({onboardingPaid:true,onboardingRefundedAt:admin.firestore.Timestamp.now()});const r=await performOnboardingActivation({db,uid:f.uid,paymentId:f.paymentId,source});assert.equal(r.ok,false);assert.equal(r.failureCode,'employee_onboarding_refunded');await noActivation(f);});
 for(const amount of [49.99,50.01])await scenario(`seller rejects genuine one-paise fee mismatch ${amount}`,async()=>{const f=await fixture(amount);await assert.rejects(()=>sellerConnect({data:{provider:'gemini',apiKey:'fixture-key',paymentId:f.paymentId},auth:f.auth}),e=>e.code==='failed-precondition');assert.equal((await db.collection('ai_connections').doc(f.uid).get()).exists,false);assert.equal((await f.paymentRef.get()).data().consumedBySellerAiActivationFor,undefined);});
 for(const kind of ['associate','seller'])for(const [field,value]of [['id','bad/path'],['amount',1],['currency','USD']])await scenario(`${kind} creator rejects provider ${field} mismatch`,async()=>{const f=await fixture(kind==='seller'?50:500);responseOverride={[field]:value};await assert.rejects(()=>(kind==='seller'?sellerCreate:associateCreate)({data:{},auth:f.auth}),e=>e.code==='failed-precondition');assert.equal((await db.collection('razorpay_orders').where('userId','==',f.uid).get()).size,0);});
 for(const amount of [Number.MAX_VALUE,500.001,0.001,Infinity,NaN,0,-1])await scenario(`unsafe fee config ${String(amount)} refuses before provider contact`,async()=>{const f=await fixture(),count=calls;await db.collection('settings').doc('associate_onboarding').update({feeAmount:amount});await assert.rejects(()=>associateCreate({data:{},auth:f.auth}),e=>e.code==='failed-precondition');assert.equal(calls,count);assert.equal((await db.collection('razorpay_orders').where('userId','==',f.uid).get()).size,0);});
 await scenario('unsupported charge currency refuses before taking money',async()=>{const f=await fixture(),count=calls;await db.collection('settings').doc('associate_onboarding').update({currency:'USD'});await assert.rejects(()=>associateCreate({data:{},auth:f.auth}),e=>e.code==='failed-precondition');assert.equal(calls,count);});
 await scenario('non-INR fee cannot activate from an INR legacy capture',async()=>{const f=await fixture();await db.collection('settings').doc('associate_onboarding').update({currency:'USD'});const r=await performOnboardingActivation({db,uid:f.uid,paymentId:f.paymentId,source:'client'});assert.equal(r.ok,false);assert.equal(r.failureCode,'config_invalid');await noActivation(f);});
 for(const purpose of ['goods_checkout','rfq_checkout','wallet_topup'])await scenario(`generic order retains declared ${purpose} against forged notes`,async()=>{const f=await fixture(100);await genericCreate({data:{amount:100,purpose,notes:{purpose:'associate_onboarding',userId:'other'}},auth:f.auth});const order=(await db.collection('razorpay_orders').doc(f.orderId).get()).data();assert.equal(order.purpose,purpose);assert.equal(order.userId,f.uid);});
 for(const purpose of ['associate_onboarding','seller_ai_activation','unknown',42,null])await scenario(`generic creator refuses privileged or invalid purpose ${purpose}`,async()=>{const f=await fixture(100),count=calls;await assert.rejects(()=>genericCreate({data:{amount:100,purpose},auth:f.auth}),e=>e.code==='invalid-argument');assert.equal(calls,count);assert.equal((await db.collection('razorpay_orders').doc(f.orderId).get()).exists,false);});
 for(const purpose of ['goods_checkout','unknown'])await scenario(`verification cannot relabel a consumed wallet payment as ${purpose}`,async()=>{
  const f=await fixture(100);
  await f.paymentRef.update({purpose:'wallet_topup',consumedByWalletTopup:f.uid});
  await db.collection('razorpay_orders').doc(f.orderId).set({orderId:f.orderId,userId:f.uid,amount:100,amountPaise:10000,currency:'INR',purpose});
  providerCapture={id:f.paymentId,order_id:f.orderId,amount:10000,currency:'INR',status:'captured',method:'upi'};
  const count=calls,signature=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${f.orderId}|${f.paymentId}`).digest('hex');
  await assert.rejects(()=>genericVerify({data:{paymentId:f.paymentId,orderId:f.orderId,signature},auth:f.auth}),e=>e.code==='failed-precondition');
  const saved=(await f.paymentRef.get()).data();assert.equal(saved.purpose,'wallet_topup');assert.equal(saved.consumedByWalletTopup,f.uid);
  if(purpose==='unknown')assert.equal(calls,count);
 });
 console.log(`FOUNDATION6 payment intent: ${passed} passed, ${failed} failed`);fft.cleanup();await admin.app().delete();process.exitCode=failed?1:0;
})().catch(e=>{console.error(e.message);process.exitCode=1;});
