process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.STORAGE_EMULATOR_HOST='http://127.0.0.1:9199';
const admin=require('firebase-admin'),assert=require('node:assert/strict'),jpeg=require('jpeg-js'),{createHash,randomUUID}=require('crypto');
const {initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc}=require('firebase/firestore'),fs=require('fs');
const {createPhotoDraft,claimPhotoCleanup,readyPhotoDraft}=require('../lib/seller/reviewPhotoDraftCore');
const {uploadPhotoRequest:upload}=require('../lib/seller/reviewPhotoUpload'),{photoInput,normalizePhoto,MAX_PHOTO_BYTES}=require('../lib/seller/reviewPhotoImage');
const project='demo-agrimore-review-photos',app=admin.initializeApp({projectId:project,storageBucket:project+'.appspot.com'}),db=app.firestore(),bucket=app.storage().bucket(),B=bucket.name;
const NOW=1000,END=1801000,pixels=Buffer.from([255,0,0,255,0,255,0,255,0,0,255,255,255,255,255,255]),image=jpeg.encode({width:2,height:2,data:pixels},90).data;
let seq=0,passed=0,failed=0;
async function test(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.message);}}
async function draft(actor='owner'){const id='upload'+(++seq),[path]=await createPhotoDraft(db,actor,id,'p',actor,['one'],NOW);return {id,path,actor};}
const request=(d,bytes=image)=>({auth:{uid:d.actor},data:{draftId:d.id,assetId:'one',imageBase64:bytes.toString('base64')}});
async function resetLimit(actor='owner'){await db.doc('review_photo_upload_limits/'+actor).delete();}
function wrapper(onSave,onMeta){return {name:B,file(path,opts){const real=bucket.file(path,opts);return {async getMetadata(){const result=await real.getMetadata();return onMeta?onMeta(result,path,opts):result;},download:real.download.bind(real),async save(bytes,options){return onSave(real,bytes,options,path,opts);}};}};}
async function run(){
 await db.doc('products/p').set({name:'Product'});
 await test('actual JPEG decode/reencode yields valid pixels',()=>{const normalized=normalizePhoto(photoInput(image.toString('base64'))),decoded=jpeg.decode(normalized);assert.equal(decoded.width,2);assert.equal(decoded.height,2);});
 for(const [name,value] of [['empty',''],['spaces',' '+image.toString('base64')],['data URI','data:image/jpeg;base64,'+image.toString('base64')],['invalid chars','!!!!'],['noncanonical pad','/x=='],['oversized',Buffer.alloc(MAX_PHOTO_BYTES+1).toString('base64')]])
  await test(name+' input refuses',()=>assert.throws(()=>photoInput(value)));
 await test('JPEG boundary bytes without actual image refuse',()=>assert.throws(()=>normalizePhoto(Buffer.from([255,216,255,217]))));
 await test('PNG bytes refuse despite JPEG request shape',()=>assert.throws(()=>normalizePhoto(Buffer.from([137,80,78,71,13,10,26,10]))));
 await test('resolution bomb rejected before huge allocation',()=>{const bytes=Buffer.from(image);let found=false;for(let i=0;i<bytes.length-9;i++)if(bytes[i]===255&&bytes[i+1]===192){bytes.writeUInt16BE(4096,i+5);bytes.writeUInt16BE(4096,i+7);found=true;break;}assert.equal(found,true);assert.throws(()=>normalizePhoto(bytes));});
 await test('appended metadata not carried to output',()=>{const bytes=Buffer.concat([image,Buffer.from('private-location-fixture')]);assert.equal(normalizePhoto(bytes).includes(Buffer.from('private-location-fixture')),false);});
 await test('actual private upload creates decoded image without token',async()=>{await resetLimit();const d=await draft(),r=await upload(db,bucket,B,request(d),()=>NOW);assert.equal(r.path,d.path);assert.equal(r.state,'uploaded');assert.deepEqual(Object.keys(r).sort(),['generation','path','state']);const [m]=await bucket.file(d.path).getMetadata();assert.equal(Object.hasOwn(m.metadata||{},'firebaseStorageDownloadTokens'),false);const [bytes]=await bucket.file(d.path).download();assert.equal(jpeg.decode(bytes).width,2);assert.equal((await db.doc('review_photo_drafts/'+d.id).get()).data().state,'open');});
 await test('same request retry preserves actual object generation',async()=>{await resetLimit();const d=await draft(),first=await upload(db,bucket,B,request(d),()=>NOW),again=await upload(db,bucket,B,request(d),()=>NOW);assert.deepEqual(again,first);});
 await test('different input cannot reuse bound asset',async()=>{await resetLimit();const d=await draft();await upload(db,bucket,B,request(d),()=>NOW);await assert.rejects(upload(db,bucket,B,request(d,Buffer.concat([image,Buffer.from('different-input')])),()=>NOW),e=>e.code==='already-exists');});
 await test('unauthenticated refuses before quota/storage',async()=>{const d=await draft('anon-test');const r=request(d);delete r.auth;await assert.rejects(upload(db,bucket,B,r,()=>NOW),e=>e.code==='unauthenticated');assert.equal((await db.doc('review_photo_upload_limits/anon-test').get()).exists,false);});
 await test('foreign actor refuses',async()=>{const d=await draft();const r=request(d);r.auth.uid='foreign';await assert.rejects(upload(db,bucket,B,r,()=>NOW));});
 for(const key of ['owner','path','bucket','generation','inputDigest'])await test('client '+key+' injection refuses',async()=>{const d=await draft();const r=request(d);r.data[key]='injected';await assert.rejects(upload(db,bucket,B,r,()=>NOW),e=>e.code==='invalid-argument');});
 await test('unleased asset refuses',async()=>{const d=await draft();const r=request(d);r.data.assetId='another';await assert.rejects(upload(db,bucket,B,r,()=>NOW));});
 await test('wrong configured bucket refuses before quota',async()=>{await resetLimit();const d=await draft();await assert.rejects(upload(db,bucket,'foreign',request(d),()=>NOW));assert.equal((await db.doc('review_photo_upload_limits/owner').get()).exists,false);});
 await test('expired lease refuses before storage',async()=>{const d=await draft();await assert.rejects(upload(db,bucket,B,request(d),()=>END),e=>e.code==='deadline-exceeded');assert.equal((await bucket.file(d.path).exists())[0],false);});
 await test('20 attempts charge before decoding, next fails quota',async()=>{await resetLimit();const d=await draft();const bad=Buffer.from([255,216,255,217]);for(let i=0;i<20;i++)await assert.rejects(upload(db,bucket,B,request(d,bad),()=>NOW),e=>e.code==='invalid-argument');await assert.rejects(upload(db,bucket,B,request(d),()=>NOW),e=>e.code==='resource-exhausted');assert.equal((await db.doc('review_photo_upload_limits/owner').get()).data().count,20);assert.equal((await bucket.file(d.path).exists())[0],false);});
 await test('quota next window resets and valid upload succeeds',async()=>{const d=await draft();assert.equal((await upload(db,bucket,B,request(d),()=>61000)).state,'uploaded');});
 await test('corrupted quota fails closed',async()=>{await db.doc('review_photo_upload_limits/owner').set({windowStart:0,count:'0'});const d=await draft();await assert.rejects(upload(db,bucket,B,request(d),()=>NOW));await resetLimit();});
 await test('save committed but response lost resolves existing object',async()=>{const d=await draft(),b=wrapper(async(real,bytes,opts)=>{await real.save(bytes,opts);throw {code:503};});assert.equal((await upload(db,b,B,request(d),()=>NOW)).state,'uploaded');});
 await test('save refusal without object remains unconfirmed',async()=>{const d=await draft(),b=wrapper(async()=>{throw {code:403};});await assert.rejects(upload(db,b,B,request(d),()=>NOW),e=>e.code==='failed-precondition');assert.equal((await db.doc('review_photo_drafts/'+d.id).get()).data().state,'open');});
 await test('actual SDK create-only and nonresumable options supplied',async()=>{const d=await draft();let observed=false;const b=wrapper(async(real,bytes,options,path,opts)=>{assert.deepEqual(opts,{preconditionOpts:{ifGenerationMatch:0}});assert.equal(options.resumable,false);assert.equal(Object.hasOwn(options.metadata.metadata,'firebaseStorageDownloadTokens'),false);observed=true;await real.save(bytes,options);});await upload(db,b,B,request(d),()=>NOW);assert.equal(observed,true);});
 await test('existing token-bearing object cannot be acknowledged',async()=>{const d=await draft();const normalized=normalizePhoto(image),hash=x=>createHash('sha256').update(x).digest('hex');await bucket.file(d.path).save(normalized,{resumable:false,metadata:{contentType:'image/jpeg',metadata:{reviewPhotoInputDigest:hash(image),reviewPhotoNormalizedDigest:hash(normalized),firebaseStorageDownloadTokens:randomUUID()}}});await assert.rejects(upload(db,bucket,B,request(d),()=>NOW));});
 await test('existing forged matching metadata with wrong bytes refuses',async()=>{const d=await draft(),normalized=normalizePhoto(image),hash=x=>createHash('sha256').update(x).digest('hex');await bucket.file(d.path).save(Buffer.alloc(normalized.length),{resumable:false,metadata:{contentType:'image/jpeg',metadata:{reviewPhotoInputDigest:hash(image),reviewPhotoNormalizedDigest:hash(normalized)}}});await assert.rejects(upload(db,bucket,B,request(d),()=>NOW));});
 await test('cleanup during save cannot confirm or publish uploaded object',async()=>{const d=await draft(),b=wrapper(async(real,bytes,opts)=>{await real.save(bytes,opts);await claimPhotoCleanup(db,d.actor,d.id,true,NOW);});await assert.rejects(upload(db,b,B,request(d),()=>NOW));assert.equal((await db.doc('review_photo_drafts/'+d.id).get()).data().state,'cleanup');assert.equal((await bucket.file(d.path).exists())[0],true);});
 await test('expiry during save leaves durable unconfirmed object',async()=>{const d=await draft();let now=NOW;const b=wrapper(async(real,bytes,opts)=>{await real.save(bytes,opts);now=END;});await assert.rejects(upload(db,b,B,request(d),()=>now),e=>e.code==='deadline-exceeded');assert.equal((await bucket.file(d.path).exists())[0],true);});
 await test('ready draft cannot reopen upload',async()=>{await resetLimit();const d=await draft();await readyPhotoDraft(db,d.actor,d.id,[{path:d.path,url:'https://fixture.invalid/photo.jpg',generation:'1'}],NOW);await assert.rejects(upload(db,bucket,B,request(d),()=>NOW));});

 await test('concurrent quota permits only remaining budget',async()=>{
  await db.doc('review_photo_upload_limits/owner').set({windowStart:0,count:19});const drafts=await Promise.all([draft(),draft(),draft(),draft()]);
  const results=await Promise.allSettled(drafts.map(d=>upload(db,bucket,B,request(d),()=>NOW)));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected'&&r.reason.code==='resource-exhausted').length,3);
  assert.equal((await db.doc('review_photo_upload_limits/owner').get()).data().count,20);await resetLimit();
 });
 await test('owners have independent upload budgets',async()=>{await db.doc('review_photo_upload_limits/owner').set({windowStart:0,count:20});const d=await draft('other-owner');assert.equal((await upload(db,bucket,B,request(d),()=>NOW)).state,'uploaded');await resetLimit();});
 await test('corrupted upload map cannot be silently replaced',async()=>{const d=await draft();await db.doc('review_photo_drafts/'+d.id).update({uploads:[]});await assert.rejects(upload(db,bucket,B,request(d),()=>NOW));assert.equal((await bucket.file(d.path).exists())[0],false);});
 const env=await initializeTestEnvironment({projectId:project,firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync('../firestore.rules','utf8')}});
 try{for(const [name,ctx] of [['owner',env.authenticatedContext('owner')],['foreign',env.authenticatedContext('foreign')],['admin',env.authenticatedContext('admin',{admin:true,role:'admin'})],['anonymous',env.unauthenticatedContext()]])
  await test(name+' denied private draft/quota client access',async()=>{for(const collection of ['review_photo_drafts','review_photo_upload_limits']){const r=doc(ctx.firestore(),collection,'owner');await assertFails(getDoc(r));await assertFails(setDoc(r,{owner:'owner'}));}});
 }finally{await env.cleanup();}
 console.log(`SUMMARY ${passed} passed ${failed} failed`);await app.delete();if(failed)process.exitCode=1;
}
run().catch(e=>{console.error(e.message);process.exitCode=1;});
