// Actual quote/hold/order Firestore transactions; trusted synthetic capture.
// No HTTP token/provider/native proof, payment API calls or production writes.
const assert=require('node:assert/strict');
for(const key of ['FIRESTORE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST','FIREBASE_STORAGE_EMULATOR_HOST'])if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env[key]||''))throw Error('Loopback emulators required');
const project=process.env.GCLOUD_PROJECT;if(!/^demo-/.test(project||''))throw Error('Demo project required');process.env.STORAGE_EMULATOR_HOST='http://'+process.env.FIREBASE_STORAGE_EMULATOR_HOST;
const admin=require('firebase-admin'),app=admin.initializeApp({projectId:project,storageBucket:project+'.appspot.com'}),db=app.firestore();
const {quoteOrderWithCredit,releaseProductCreditHold}=require('../lib/customer/productCreditHold'),{createOrder}=require('../lib/customer/createOrder');
let seq=0,passed=0,failed=0;const auth=uid=>({uid,token:{}});
async function gates(enabled=true){await db.doc('compliance_config/benefit_program').set({legalReviewStatus:'APPROVED',complianceApprovalStatus:'APPROVED'});await db.doc('feature_flags/benefit_program').set({BENEFIT_PROGRAM_ENABLED:enabled,PRODUCT_CREDIT_REDEMPTION_ENABLED:enabled});}
async function fixture(credit=20){const uid='hold-contract-'+(++seq),product='hold-product-'+seq,program='hold-program-'+seq;await gates();await db.doc('users/'+uid).set({uid,profileCompleted:true});await db.doc('sellers/seller-'+seq).set({status:'approved',isActive:true});await db.doc('products/'+product).set({name:'Synthetic product',salePrice:100,sellerId:'seller-'+seq,isActive:true,stock:10,stockQuantity:10,isB2BEnabled:false,images:[]});await db.doc('benefit_programs/'+program).set({status:'active',durationMonths:12,rulesVersion:1,benefitRuleType:'flatRupee',benefitRateValue:500,creditFrequency:'monthly',minProgramAmount:0,maxProgramAmount:0,redemptionEnabled:true,minOrderValueForRedemption:0,maxCreditPerOrder:null,maxCreditPercentOfOrder:null,redeemableCategoryIds:null});await db.doc('benefit_enrollments/'+uid).set({customerId:uid,programId:program,status:'active',programAmount:100000,rulesVersionAtEnrollment:1,startDate:admin.firestore.Timestamp.fromMillis(Date.now()-86400000),maturityDate:admin.firestore.Timestamp.fromMillis(Date.now()+86400000*365)});await db.doc('product_credit_balances/'+uid).set({available:credit,pending:0,onHold:0,lifetimeEarned:credit,lifetimeUsed:0,lifetimeExpired:0});return {uid,product,items:[{productId:product,quantity:1}]};}
const quote=u=>quoteOrderWithCredit.run({auth:auth(u.uid),data:{items:u.items,orderMode:'B2C'}});
const create=(u,q,extra={})=>createOrder.run({auth:auth(u.uid),data:{items:u.items,orderMode:'B2C',paymentMethod:'cod',productCreditHoldId:q.holdId,...extra}});
async function capture(u,q){const id='pay_hold_'+seq,orderId='order_hold_'+seq;await db.doc('verified_payments/'+id).set({paymentId:id,orderId,userId:u.uid,status:'captured',amount:q.payable,amountPaise:Math.round(q.payable*100),currency:'INR',purpose:'goods_checkout',providerMode:'live',providerCaptureVerified:true,isTest:false});return {paymentMethod:'razorpay',razorpayPaymentId:id,razorpayOrderId:orderId};}
async function snapshot(u,payment){const names=['product_credit_balances/'+u.uid,'products/'+u.product,...(payment?['verified_payments/'+payment.razorpayPaymentId]:[])];const docs=await Promise.all(names.map(p=>db.doc(p).get()));return {docs:docs.map(d=>({path:d.ref.path,data:d.data()})),ledger:(await db.collection('product_credit_ledger').where('customerId','==',u.uid).get()).docs.map(d=>({id:d.id,data:d.data()})),orders:(await db.collection('orders').where('userId','==',u.uid).get()).docs.map(d=>d.id)};}
async function check(name,body){try{await body();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function run(){
 await check('numeric deadline matches stored timestamp, legacy ISO and literal30minute TTL',async()=>{const u=await fixture(),before=Date.now(),q=await quote(u),after=Date.now(),h=(await db.doc('product_credit_holds/'+q.holdId).get()).data();assert.equal(q.creditApplied,20);assert.equal(q.payable,80);assert.equal(q.productCreditHoldExpiresAtMs,h.expiresAt.toMillis());assert.equal(Date.parse(q.expiresAt),q.productCreditHoldExpiresAtMs);assert.ok(Number.isSafeInteger(q.productCreditHoldExpiresAtMs));assert.ok(q.productCreditHoldExpiresAtMs>=before+1800000&&q.productCreditHoldExpiresAtMs<=after+1800000);});
 await check('no credit quote has no numeric or ISO deadline',async()=>{const u=await fixture(0),q=await quote(u);assert.equal(q.holdId,null);assert.equal(q.expiresAt,null);assert.equal(q.productCreditHoldExpiresAtMs,null);assert.equal((await db.collection('product_credit_holds').where('customerId','==',u.uid).get()).size,0);});
 await check('disabled gates return ordinary payable with no hold deadline',async()=>{const u=await fixture();await gates(false);const q=await quote(u);assert.equal(q.creditApplied,0);assert.equal(q.payable,100);assert.equal(q.productCreditHoldExpiresAtMs,null);assert.equal(q.holdId,null);});
 await check('current partial credit and captured payment settle atomically',async()=>{const u=await fixture(),q=await quote(u),p=await capture(u,q),r=await create(u,q,p);assert.equal(r.orders.length,1);const h=(await db.doc('product_credit_holds/'+q.holdId).get()).data(),pay=(await db.doc('verified_payments/'+p.razorpayPaymentId).get()).data(),balance=(await db.doc('product_credit_balances/'+u.uid).get()).data();assert.equal(h.status,'settled');assert.equal(pay.consumedByOrderId,r.orders[0].orderId);assert.equal(balance.onHold,0);assert.equal(balance.lifetimeUsed,20);});
 await check('full credit settles without provider payment',async()=>{const u=await fixture(100),q=await quote(u),r=await create(u,q,{paymentMethod:'razorpay'});assert.equal(q.payable,0);assert.equal(r.orders.length,1);assert.equal((await db.doc('product_credit_holds/'+q.holdId).get()).data().status,'settled');});
 for(const state of ['active-expired','released','expired'])await check('captured '+state+' hold refuses with ledger/payment/stock intact',async()=>{const u=await fixture(),q=await quote(u),p=await capture(u,q),ref=db.doc('product_credit_holds/'+q.holdId);if(state==='active-expired')await ref.update({expiresAt:admin.firestore.Timestamp.fromMillis(Date.now()-1)});else if(state==='released')await releaseProductCreditHold.run({auth:auth(u.uid),data:{holdId:q.holdId,reason:'Synthetic abandoned checkout'}});else await ref.update({status:'expired'});const before=await snapshot(u,p),holdBefore=(await ref.get()).data();await assert.rejects(()=>create(u,q,p),e=>e.code==='failed-precondition'&&/hold/i.test(e.message));assert.deepEqual(await snapshot(u,p),before);assert.deepEqual((await ref.get()).data(),holdBefore);assert.equal(before.orders.length,0);assert.equal(before.docs.find(x=>x.path.startsWith('verified_payments/')).data.consumedByOrderId,undefined);});
 await check('expired hold without paid capture cannot create COD order',async()=>{const u=await fixture(),q=await quote(u),ref=db.doc('product_credit_holds/'+q.holdId);await ref.update({expiresAt:admin.firestore.Timestamp.fromMillis(Date.now()-1)});const before=await snapshot(u);await assert.rejects(()=>create(u,q),e=>e.code==='failed-precondition');assert.deepEqual(await snapshot(u),before);});
 await check('new live deadline does not let another actor consume hold',async()=>{const u=await fixture(),q=await quote(u);await db.doc('users/other-contract-actor').set({profileCompleted:true});const before=await snapshot(u);await assert.rejects(()=>createOrder.run({auth:auth('other-contract-actor'),data:{items:u.items,orderMode:'B2C',paymentMethod:'cod',productCreditHoldId:q.holdId}}),e=>e.code==='permission-denied');assert.deepEqual(await snapshot(u),before);});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Fixture failure: '+e.name+' '+e.message);process.exitCode=1;}).finally(()=>app.delete());
