// Real compiled scheduler/Admin SDK on isolated loopback demo projects only.
// Query transport failure is synthetic; population changes are real demo writes.
const assert=require('node:assert/strict');
if(!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Loopback emulator required');
process.env.GCLOUD_PROJECT='demo-rider-account-pages';
const admin=require('firebase-admin');admin.initializeApp({projectId:process.env.GCLOUD_PROJECT});
const {Query,Timestamp}=require('firebase-admin/firestore');
const M=require('../lib/delivery/riderMoney'),{statementCutoff}=require('../lib/delivery/riderPay');
const NOW=Date.UTC(2026,9,5,1),{cutoffMs}=statementCutoff(NOW);let seq=0,passed=0,failed=0;
const id=i=>'rider_'+String(i).padStart(4,'0');
async function scenario(label,fn){const app=admin.initializeApp({projectId:`demo-rider-pages-${++seq}`},`rider-page-${seq}`),db=app.firestore();try{await fn(db);passed++;console.log('PASS '+label);}catch(e){failed++;console.log('FAIL '+label+': '+e.message);}finally{await db.terminate();await app.delete();}}
async function seed(db,count,earnings=[]){const batch=db.batch();for(let i=0;i<count;i++)batch.set(db.doc(`rider_accounts/${id(i)}`),{riderId:id(i),cashHeldPaise:0,earningsUnsettledPaise:earnings.includes(i)?100:0,unusedSensitiveFixture:'must not be retained'});for(const i of earnings){batch.set(db.doc(`delivery_partners/${id(i)}`),{upiId:'fixture@example.invalid'});batch.set(db.doc(`rider_earnings/${id(i)}_order`),{riderId:id(i),totalPaise:100,statementId:null,createdAt:Timestamp.fromMillis(cutoffMs-1000)});}await batch.commit();}
function trace(db,{afterPage,failPage}={}){
 const reads={pages:[],accountIds:[],readOnlyOptions:[],readOnlyWrites:0};const original=Query.prototype.get;
 async function page(ref,read,readonly){const n=reads.pages.length+1;if(n===failPage)throw Error('Synthetic account page transport failure');const snap=await read();reads.pages.push({size:snap.size,readonly,keys:snap.docs.map(d=>Object.keys(d.data()))});if(afterPage)await afterPage(n,snap);return snap;}
 Query.prototype.get=function(...args){return this._queryOptions.collectionId==='rider_accounts'?page(this,()=>original.apply(this,args),false):original.apply(this,args);};
 const wrapped=new Proxy(db,{get(target,key){if(key==='runTransaction')return (callback,options)=>{if(options?.readOnly)reads.readOnlyOptions.push(options);return target.runTransaction(tx=>callback(new Proxy(tx,{get(t,k){if(k==='get')return(ref,...args)=>{if(ref._queryOptions?.collectionId==='rider_accounts')return page(ref,()=>t.get(ref,...args),options?.readOnly===true);if(ref.path?.startsWith('rider_accounts/'))reads.accountIds.push(ref.id);return t.get(ref,...args);};if(['create','set','update','delete'].includes(k)&&options?.readOnly)return(...args)=>{reads.readOnlyWrites++;return t[k](...args);};const v=t[k];return typeof v==='function'?v.bind(t):v;}})),options);};const v=target[key];return typeof v==='function'?v.bind(target):v;}});
 return {db:wrapped,reads,restore(){Query.prototype.get=original;}};
}
async function traced(db,options,fn){const t=trace(db,options);try{return await fn(t);}finally{t.restore();}}
function bounded(t){assert.ok(t.reads.pages.every(p=>p.size<=100),'account page exceeds 100 records');assert.ok(t.reads.pages.every(p=>p.keys.every(k=>k.length===0)),'account query retains unnecessary fields');assert.ok(t.reads.pages.every(p=>p.readonly),'account reads must share a readOnly transaction');assert.equal(t.reads.readOnlyOptions.length,1);assert.equal(t.reads.readOnlyWrites,0);}
const notices=(db,rider)=>db.collection(`users/${rider}/notifications`).get();
(async()=>{
 await scenario('all 205 accounts processed exactly once in bounded projected snapshot pages',async db=>{await seed(db,205);await traced(db,{},async t=>{assert.deepEqual(await M.buildAllStatements(t.db,NOW),{created:0,exists:0,nothing:205,failed:0});bounded(t);assert.deepEqual(t.reads.pages.map(p=>p.size),[100,100,5]);assert.deepEqual(t.reads.accountIds,Array.from({length:205},(_,i)=>id(i)));});});
 await scenario('empty enumeration terminates without rider writes',async db=>{await traced(db,{},async t=>{assert.deepEqual(await M.buildAllStatements(t.db,NOW),{created:0,exists:0,nothing:0,failed:0});bounded(t);assert.deepEqual(t.reads.pages.map(p=>p.size),[0]);});});
 await scenario('exact full page performs terminating empty read',async db=>{await seed(db,100);await traced(db,{},async t=>{const v=await M.buildAllStatements(t.db,NOW);assert.equal(v.nothing,100);bounded(t);assert.deepEqual(t.reads.pages.map(p=>p.size),[100,0]);});});
 await scenario('money, hold, COD netting and inbox effects remain correct across pages',async db=>{await seed(db,205,[0,100,204]);await db.doc(`rider_accounts/${id(100)}`).update({bankChangePending:'fixture_change'});await db.doc(`rider_accounts/${id(204)}`).update({cashHeldPaise:50});await traced(db,{},async t=>{assert.deepEqual(await M.buildAllStatements(t.db,NOW),{created:3,exists:0,nothing:202,failed:0});bounded(t);});const payouts=await db.collection('rider_payouts').get();assert.equal(payouts.size,3);const byId=new Map(payouts.docs.map(d=>[d.data().riderId,d.data()]));assert.equal(byId.get(id(0)).amountPaise,100);assert.equal(byId.get(id(100)).status,'on_hold');assert.equal(byId.get(id(100)).holdReason,'bank_change_pending');assert.equal(byId.get(id(204)).amountPaise,50);assert.equal(byId.get(id(204)).nettedPaise,50);for(const i of [0,100,204])assert.equal((await notices(db,id(i))).size,1);});
 await scenario('scheduler retry preserves balances and does not duplicate notices',async db=>{await seed(db,105,[0,104]);await M.buildAllStatements(db,NOW);const before=(await db.doc(`rider_accounts/${id(104)}`).get()).data();await traced(db,{},async t=>{assert.deepEqual(await M.buildAllStatements(t.db,NOW+1000),{created:0,exists:2,nothing:105,failed:0});bounded(t);});assert.deepEqual((await db.doc(`rider_accounts/${id(104)}`).get()).data(),before);for(const i of [0,104])assert.equal((await notices(db,id(i))).size,1);});
 await scenario('real concurrent addition and deletion preserve initial enumeration membership',async db=>{await seed(db,205);await traced(db,{afterPage:async n=>{if(n===1){const b=db.batch();b.delete(db.doc(`rider_accounts/${id(150)}`));b.set(db.doc('rider_accounts/zz_late_rider'),{cashHeldPaise:0});await b.commit();}}},async t=>{const v=await M.buildAllStatements(t.db,NOW);assert.equal(v.nothing,205);assert.deepEqual(t.reads.accountIds,Array.from({length:205},(_,i)=>id(i)));assert.ok(!t.reads.accountIds.includes('zz_late_rider'));bounded(t);});});
 await scenario('second page failure propagates and retry recovers remaining effects exactly once',async db=>{await seed(db,105,[0,104]);await traced(db,{failPage:2},async t=>{await assert.rejects(M.buildAllStatements(t.db,NOW),/Synthetic account page transport failure/);assert.equal((await db.collection('rider_payouts').get()).size,1);assert.equal((await notices(db,id(0))).size,1);});await traced(db,{},async t=>{assert.deepEqual(await M.buildAllStatements(t.db,NOW),{created:1,exists:1,nothing:104,failed:0});bounded(t);});assert.equal((await db.collection('rider_payouts').get()).size,2);for(const i of [0,104])assert.equal((await notices(db,id(i))).size,1);});
 await scenario('individual malformed account fails safely while later page riders continue',async db=>{await seed(db,105,[104]);await db.doc(`rider_accounts/${id(2)}`).update({cashHeldPaise:'corrupt'});await traced(db,{},async t=>{assert.deepEqual(await M.buildAllStatements(t.db,NOW),{created:1,exists:0,nothing:103,failed:1});bounded(t);});assert.equal((await db.collection('rider_payouts').get()).size,1);assert.equal((await notices(db,id(104))).size,1);});
 console.log(`RESULT ${passed} passed; ${failed} failed`);await admin.app().delete();if(failed)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
