// Compiled bank-change cores + actual Admin SDK on isolated loopback demo only.
// Query/commit refusal is synthetic; no provider or production document access.
const assert=require('node:assert/strict');
if(!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Loopback emulator required');
process.env.GCLOUD_PROJECT='demo-bank-query-pages';const admin=require('firebase-admin');admin.initializeApp({projectId:process.env.GCLOUD_PROJECT});
const db=admin.firestore(),M=require('../lib/delivery/riderMoney');const NOW=Date.UTC(2026,9,5,3),proposal={upiId:'newfixture@upi'};let seq=0,passed=0,failed=0;const evidence=[];
async function scenario(label,fn){try{await fn();passed++;console.log('PASS '+label);}catch(e){failed++;console.log('FAIL '+label+': '+e.message);}}
async function fixture(count,{review=false,manual=0,payload=128,destination=true}={}){const rider=`bank_pages_${++seq}`,request=`bank_pages_req_${seq}`,b=db.batch();b.set(db.doc(`delivery_partners/${rider}`),destination?{upiId:'oldfixture@upi'}:{});b.set(db.doc(`rider_accounts/${rider}`),{riderId:rider,cashHeldPaise:17,earningsUnsettledPaise:123,bankChangePending:review?request:null});if(review)b.set(db.doc(`rider_bank_change_requests/${request}`),{riderId:rider,...proposal,status:'pending'});await b.commit();for(let n=0;n<count;n+=200){const batch=db.batch();for(let i=n;i<Math.min(n+200,count);i++)batch.set(db.doc(`rider_payouts/${rider}_${String(i).padStart(5,'0')}`),{riderId:rider,status:review?'on_hold':'pending',holdReason:review?(i<manual?'manual_review':i%2?'no_bank_details':'bank_change_pending'):null,amountPaise:101+i,unusedPayload:'x'.repeat(payload)});await batch.commit();}await db.doc(`rider_payouts/${rider}_foreign`).set({riderId:'foreign_fixture',status:review?'on_hold':'pending',holdReason:'bank_change_pending',amountPaise:222});return{rider,request,count};}
async function records(f){const q=await db.collection('rider_payouts').where('riderId','==',f.rider).get();return q.docs.map(d=>({id:d.id,...d.data()}));}
async function state(f){return{account:(await db.doc(`rider_accounts/${f.rider}`).get()).data(),partner:(await db.doc(`delivery_partners/${f.rider}`).get()).data(),requests:(await db.collection('rider_bank_change_requests').where('riderId','==',f.rider).get()).docs.map(d=>({id:d.id,...d.data()})),payouts:await records(f)};}
async function traced(options,fn){const reads={pages:[],commits:[]},original=db.request;
 db.request=function(method,req,...args){if(method==='commit'){reads.commits.push({writes:req.writes?.length||0,jsonBytes:Buffer.byteLength(JSON.stringify(req),'utf8')});if(options.rejectCommit)throw Error('Synthetic bank commit refusal');}const result=original.call(db,method,req,...args);if(method==='commit'&&options.loseCommitResponse&&req.writes?.length)return Promise.resolve(result).then(()=>{throw Error('Synthetic response lost after actual commit');});return result;};
 const wrapped=new Proxy(db,{get(target,key){if(key==='runTransaction')return(callback,txOptions)=>target.runTransaction(tx=>{const pointReads=[];return callback(new Proxy(tx,{get(t,k){if(k==='get')return async(ref,...args)=>{if(ref.path){const p=t.get(ref,...args);pointReads.push(p);return p;}const snap=await t.get(ref,...args);reads.pages.push({size:snap.size,keys:snap.docs.map(d=>Object.keys(d.data()))});if(reads.pages.length===options.rejectPage){await Promise.allSettled(pointReads);throw Error('Synthetic bank page refusal');}return snap;};const v=t[k];return typeof v==='function'?v.bind(t):v;}}));},txOptions);const v=target[key];return typeof v==='function'?v.bind(target):v;}});
 try{return await fn({db:wrapped,reads});}finally{db.request=original;}
}
function bounded(t,review=false){assert.ok(t.reads.pages.every(x=>x.size<=100),'query page exceeds 100 documents');assert.ok(t.reads.pages.every(x=>x.keys.every(k=>review?k.every(n=>n==='holdReason'):k.length===0)),'query includes unused payout payload');}
(async()=>{
 await scenario('request holds all 1253 own payouts atomically with ID-only pages',async()=>{const f=await fixture(1253),before=await records(f);await traced({},async t=>{const v=await M.requestBankChangeCore(t.db,f.rider,proposal,NOW);assert.equal(v.kind,'requested');const after=await records(f);assert.equal(after.length,1253);assert.ok(after.every(x=>x.status==='on_hold'&&x.holdReason==='bank_change_pending'));assert.deepEqual(after.map(x=>x.amountPaise),before.map(x=>x.amountPaise));assert.equal((await db.doc(`rider_payouts/${f.rider}_foreign`).get()).data().status,'pending');assert.equal(t.reads.commits.length,1);assert.equal(t.reads.commits[0].writes,1255);evidence.push({operation:'request1253',...t.reads.commits[0],pages:t.reads.pages.map(x=>x.size)});bounded(t);assert.equal(t.reads.pages.length,13);});});
 await scenario('review releases all eligible rows beyond page boundaries, never manual or foreign holds',async()=>{const f=await fixture(1277,{review:true,manual:173}),before=await records(f);await traced({},async t=>{assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW),{kind:'approved',released:1104});const after=await records(f);assert.equal(after.filter(x=>x.status==='on_hold').length,173);assert.equal(after.filter(x=>x.status==='pending').length,1104);assert.deepEqual(after.map(x=>x.amountPaise),before.map(x=>x.amountPaise));assert.equal((await db.doc(`rider_payouts/${f.rider}_foreign`).get()).data().status,'on_hold');assert.equal(t.reads.commits.length,1);assert.equal(t.reads.commits[0].writes,1107);evidence.push({operation:'review1277',...t.reads.commits[0],pages:t.reads.pages.map(x=>x.size)});bounded(t,true);assert.equal(t.reads.pages.length,13);});});
 await scenario('empty and exact-page request traversal terminates without truncation',async()=>{for(const count of [0,100]){const f=await fixture(count);await traced({},async t=>{assert.equal((await M.requestBankChangeCore(t.db,f.rider,proposal,NOW)).kind,'requested');bounded(t);assert.deepEqual(t.reads.pages.map(x=>x.size),count?[100,0]:[0]);});}});
 await scenario('review projection excludes large unrelated values while keeping every valid hold',async()=>{const f=await fixture(103,{review:true,payload:32768});await traced({},async t=>{assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW),{kind:'approved',released:103});bounded(t,true);assert.deepEqual(t.reads.pages.map(x=>x.size),[100,3]);});});
 await scenario('not-a-rider request refuses before payout queries',async()=>{await traced({},async t=>{assert.deepEqual(await M.requestBankChangeCore(t.db,'missing_fixture_rider',proposal,NOW),{kind:'refused',reason:'not_a_rider'});assert.equal(t.reads.pages.length,0);assert.equal(t.reads.commits.filter(c=>c.writes>0).length,0);});});
 await scenario('already-pending request refuses before payout queries and preserves state',async()=>{const f=await fixture(103,{review:true}),before=await state(f);await traced({},async t=>{assert.deepEqual(await M.requestBankChangeCore(t.db,f.rider,proposal,NOW),{kind:'refused',reason:'already_pending'});assert.equal(t.reads.pages.length,0);assert.equal(t.reads.commits.filter(c=>c.writes>0).length,0);});assert.deepEqual(await state(f),before);});
 for(const review of [false,true])await scenario(`second ${review?'review':'request'} page failure has no effects; full retry recovers`,async()=>{const f=await fixture(203,{review}),before=await state(f);await traced({rejectPage:2},async t=>{await assert.rejects(review?M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW):M.requestBankChangeCore(t.db,f.rider,proposal,NOW),/Synthetic bank page refusal/);assert.equal(t.reads.commits.length,0);});assert.deepEqual(await state(f),before);await traced({},async t=>{const v=review?await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW):await M.requestBankChangeCore(t.db,f.rider,proposal,NOW);assert.equal(v.kind,review?'approved':'requested');if(review)assert.equal(v.released,203);bounded(t,review);});});
 for(const review of [false,true])await scenario(`synthetic ${review?'review':'request'} commit refusal is atomic and recoverable`,async()=>{const f=await fixture(103,{review}),before=await state(f);await traced({rejectCommit:true},async t=>{await assert.rejects(review?M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW):M.requestBankChangeCore(t.db,f.rider,proposal,NOW),/Synthetic bank commit refusal/);assert.equal(t.reads.commits.length,1);});assert.deepEqual(await state(f),before);await traced({},async t=>{const v=review?await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW):await M.requestBankChangeCore(t.db,f.rider,proposal,NOW);assert.equal(v.kind,review?'approved':'requested');bounded(t,review);});});
 await scenario('rejection with no current destination changes no held status',async()=>{const f=await fixture(203,{review:true,destination:false});await traced({},async t=>{assert.deepEqual(await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,false,'Fixture rejection',NOW),{kind:'rejected',released:0});assert.ok((await records(f)).every(x=>x.status==='on_hold'));bounded(t,true);});});
 for(const review of [false,true])await scenario(`lost ${review?'review':'request'} response after real commit does not duplicate economic effects`,async()=>{const f=await fixture(103,{review});await traced({loseCommitResponse:true},async t=>{await assert.rejects(review?M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW):M.requestBankChangeCore(t.db,f.rider,proposal,NOW),/Synthetic response lost after actual commit/);assert.equal(t.reads.commits.length,1);});const committed=await state(f);assert.ok(committed.payouts.every(p=>p.status===(review?'pending':'on_hold')));assert.equal(committed.requests.length,1);assert.equal(committed.requests[0].status,review?'approved':'pending');if(review){assert.equal(committed.account.bankChangePending,null);assert.equal(committed.partner.upiId,proposal.upiId);}else{assert.equal(committed.account.bankChangePending,committed.requests[0].id);assert.equal(committed.partner.upiId,'oldfixture@upi');}await traced({},async t=>{const retry=review?await M.reviewBankChangeCore(t.db,'fixture_admin',f.request,true,null,NOW+1):await M.requestBankChangeCore(t.db,f.rider,proposal,NOW+1);assert.deepEqual(retry,{kind:'refused',reason:review?'not_pending':'already_pending'});assert.equal(t.reads.pages.length,0);assert.equal(t.reads.commits.filter(x=>x.writes>0).length,0);});assert.deepEqual(await state(f),committed);});
 await scenario('request repeat and reviewed retry retain historical refusal semantics',async()=>{const f=await fixture(103);const v=await M.requestBankChangeCore(db,f.rider,proposal,NOW);assert.equal(v.kind,'requested');assert.deepEqual(await M.requestBankChangeCore(db,f.rider,proposal,NOW+1),{kind:'refused',reason:'already_pending'});await M.reviewBankChangeCore(db,'fixture_admin',v.id,true,null,NOW+2);assert.deepEqual(await M.reviewBankChangeCore(db,'fixture_admin',v.id,true,null,NOW+3),{kind:'refused',reason:'not_pending'});});
 console.log('CAPACITY_EVIDENCE '+JSON.stringify({runtime:process.version,commitBytesBasis:'JSON UTF8 of SDK request, NOT protobuf wire/API/index-entry cost or heap',evidence}));console.log(`RESULT ${passed} passed; ${failed} failed`);await db.terminate();if(failed)process.exitCode=1;
})().catch(async e=>{console.error(e.stack);await db.terminate();process.exitCode=1;});
