// Real demo transactions + canonical ledger helper; trusted callable contexts.
// No provider/JWT/production or forced post-read conflict proof.
const assert=require('node:assert/strict');
for(const k of ['FIRESTORE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST','FIREBASE_STORAGE_EMULATOR_HOST'])if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env[k]||''))throw Error('Loopback required');
const project=process.env.GCLOUD_PROJECT;if(!/^demo-/.test(project||''))throw Error('Demo project required');process.env.STORAGE_EMULATOR_HOST='http://'+process.env.FIREBASE_STORAGE_EMULATOR_HOST;
const admin=require('firebase-admin'),app=admin.initializeApp({projectId:project,storageBucket:project+'.appspot.com'}),db=app.firestore();
const {appendLedgerEntry,toProjectionFields}=require('../lib/customer/productCreditLedger'),reconcile=require('../lib/customer/productCreditExpiry').reconcileProductCreditBalances;
let seq=0,passed=0,failed=0;
async function post(uid,type,amount,relatedEntryId=null,metadata=null){return db.runTransaction(async tx=>{const p=await tx.get(db.doc('product_credit_balances/'+uid));return appendLedgerEntry(tx,db,{customerId:uid,enrollmentId:'',type,amount,currentProjection:toProjectionFields(p.data()),relatedEntryId,metadata,description:'Synthetic legitimate ledger event'});});}
async function fixture(){const uid='reconcile-fixture-'+(++seq);await post(uid,'CREDIT',10);return uid;}
const call=uid=>reconcile.run({auth:{uid:'demo-credit-admin',token:{admin:true}},data:{customerId:uid,reason:'Synthetic projection review'}});
async function rows(uid){return (await db.collection('product_credit_ledger').where('customerId','==',uid).get()).docs.map(d=>({id:d.id,data:d.data()}));}
async function audit(uid){return (await db.collection('compliance_audit_log').where('target','==',uid).get()).docs.map(d=>d.data());}
async function available(uid){return (await db.doc('product_credit_balances/'+uid).get()).data().available;}
async function unchanged(uid){const before=await rows(uid),n=await available(uid);assert.equal((await call(uid)).driftsFound,0);assert.equal(await available(uid),n);assert.deepEqual(await rows(uid),before);assert.equal((await audit(uid)).length,0);}
async function race(type){const uid=await fixture();let related=null;if(type==='RELEASE')related=(await post(uid,'HOLD',5)).entryRef.id;if(type==='REVERSAL')related=(await post(uid,'REDEMPTION',5)).entryRef.id;const original=db.runTransaction;let fired=false,expected,ledger;db.runTransaction=async function(fn,...args){if(!fired){fired=true;expected=(await post(uid,type,5,related)).newProjection.available;ledger=await rows(uid);}return original.call(this,fn,...args);};let r;try{r=await call(uid);}finally{db.runTransaction=original;}assert.equal(fired,true);const after=await available(uid),second=await call(uid);if(after!==expected)console.log('OBSERVED spurious correction: event='+type+' expected='+expected+' actual='+after+' nextDrifts='+second.driftsFound);assert.equal(after,expected);assert.equal(r.driftsFound,0);assert.equal(second.driftsFound,0);assert.deepEqual(await rows(uid),ledger);assert.equal((await audit(uid)).length,0);}
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function run(){
 await db.doc('users/demo-credit-admin').set({role:'admin'});
 for(const type of ['CREDIT','HOLD','RELEASE','REVERSAL'])await check('legitimate '+type+' at reconciliation boundary survives without adjustment',()=>race(type));
 await check('held redemption is not deducted from available a second time',async()=>{const uid=await fixture(),h=await post(uid,'HOLD',5);await post(uid,'REDEMPTION',5,h.entryRef.id);await unchanged(uid);assert.equal(await available(uid),5);});
 await check('direct redemption still deducts available exactly once',async()=>{const uid=await fixture();await post(uid,'REDEMPTION',5);await unchanged(uid);assert.equal(await available(uid),5);});
 await check('held redemption reversal restores available without phantom adjustment',async()=>{const uid=await fixture(),h=await post(uid,'HOLD',5),r=await post(uid,'REDEMPTION',5,h.entryRef.id);await post(uid,'REVERSAL',5,r.entryRef.id);await unchanged(uid);assert.equal(await available(uid),10);});
 await check('released hold restores available without adjustment',async()=>{const uid=await fixture(),h=await post(uid,'HOLD',5);await post(uid,'RELEASE',5,h.entryRef.id);await unchanged(uid);});
 for(const drifted of [9,11])await check('genuine cache drift '+drifted+' repairs once without minting or burning ledger credit',async()=>{const uid=await fixture();await db.doc('product_credit_balances/'+uid).update({available:drifted});const before=(await db.doc('product_credit_balances/'+uid).get()).data(),r=await call(uid),first=await available(uid),second=await call(uid),final=await available(uid);if(final!==10)console.log('OBSERVED recurring repair: first='+first+' second='+final+' secondDrifts='+second.driftsFound);assert.equal(r.driftsFound,1);assert.equal(first,10);assert.equal(final,10);assert.equal(second.driftsFound,0);const ledger=await rows(uid),adjust=ledger.filter(x=>x.data.type==='ADJUSTMENT');assert.equal(adjust.length,1);assert.equal(adjust[0].data.amount,0);assert.equal(adjust[0].data.metadata.projectionRepair,true);assert.equal((await audit(uid)).length,1);const after=(await db.doc('product_credit_balances/'+uid).get()).data();for(const k of ['pending','onHold','lifetimeEarned','lifetimeUsed','lifetimeExpired'])assert.equal(after[k],before[k]);});
 await check('valid economic adjustment remains part of ledger truth',async()=>{const uid=await fixture();await post(uid,'ADJUSTMENT',2,null,{direction:'debit'});await unchanged(uid);assert.equal(await available(uid),8);});
 for(const malformed of [{type:'UNKNOWN',amount:5},{type:'CREDIT',amount:'5'},{type:'CREDIT',amount:-5},{type:'CREDIT',amount:NaN},{type:'ADJUSTMENT',amount:5,metadata:{direction:'unknown'}}])await check('malformed ledger row '+malformed.type+' '+String(malformed.amount)+' refuses without adjustment',async()=>{const uid=await fixture();await db.doc('product_credit_ledger/bad-'+seq).set({customerId:uid,...malformed});const before=await rows(uid),balance=await available(uid);await assert.rejects(()=>call(uid),e=>e.code==='failed-precondition');assert.deepEqual(await rows(uid),before);assert.equal(await available(uid),balance);assert.equal((await audit(uid)).length,0);});
 await check('missing reason refuses before economic writes',async()=>{const uid=await fixture(),before=await rows(uid);await assert.rejects(()=>reconcile.run({auth:{uid:'demo-credit-admin',token:{admin:true}},data:{customerId:uid}}),e=>e.code==='invalid-argument');assert.deepEqual(await rows(uid),before);});
 await check('ordinary owner cannot invoke admin reconciliation',async()=>{const uid=await fixture(),before=await rows(uid);await assert.rejects(()=>reconcile.run({auth:{uid,token:{}},data:{customerId:uid,reason:'Synthetic request'}}),e=>e.code==='permission-denied');assert.deepEqual(await rows(uid),before);assert.equal(await available(uid),10);});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Fixture failure: '+e.name+' '+e.message);process.exitCode=1;}).finally(()=>app.delete());
