// Synthetic loopback SDK/transactions/rules and faithful conditional failure doubles only.
// Capability and download URL values are compared in memory, never printed or persisted.
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.STORAGE_EMULATOR_HOST='http://127.0.0.1:9199';
const admin=require('firebase-admin'),assert=require('node:assert/strict'),jpeg=require('jpeg-js'),{createHash,randomUUID}=require('crypto'),fs=require('fs'),path=require('path');
const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,updateDoc}=require('firebase/firestore');
const core=require('../lib/seller/reviewPhotoDraftCore'),{uploadPhotoRequest:upload}=require('../lib/seller/reviewPhotoUpload'),{publishPhotoRequest:publish}=require('../lib/seller/reviewPhotoPublication');
const P='demo-agrimore-photo-publication',app=admin.initializeApp({projectId:P,storageBucket:P+'.appspot.com'}),db=app.firestore(),bucket=app.storage().bucket(),B=bucket.name;
const NOW=1000,END=1801000,image=jpeg.encode({width:1,height:1,data:Buffer.from([200,80,30,255])},90).data;
let seq=0,passed=0,failed=0,env;
const hash=b=>createHash('sha256').update(b).digest('hex');
const record=d=>db.doc('review_photo_drafts/'+d.id),review=d=>db.doc('products/p/reviews/'+d.actor);
const client=d=>doc(env.authenticatedContext(d.actor).firestore(),'products/p/reviews/'+d.actor);
const request=d=>({auth:{uid:d.actor},data:{draftId:d.id,rating:4,title:'Title',comment:'Comment'}});
async function draft(assets=['one'],uploaded=true){const id='publication'+(++seq),actor='actor'+seq;await db.doc('products/p').set({name:'Synthetic product'});await db.doc('users/'+actor).set({name:'Original profile',photoUrl:'https://fixture.invalid/avatar'});const paths=await core.createPhotoDraft(db,actor,id,'p',actor,assets,NOW),d={id,actor,paths};if(uploaded)for(const assetId of assets)await upload(db,bucket,B,{auth:{uid:actor},data:{draftId:id,assetId,imageBase64:image.toString('base64')}},()=>NOW);return d;}
function adapt(patch,read){const calls=[];return {name:B,calls,file(p,opts){calls.push({p,opts});const f=bucket.file(p,opts);return {async getMetadata(){const result=await f.getMetadata();return read?read(result,p,opts):result;},download:f.download.bind(f),async setMetadata(m,o){return patch?patch(f,m,o,p,opts):f.setMetadata(m,o);}};}};}
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+(e.code||e.name)+' '+e.message);}}
async function denied(action,code){await assert.rejects(action,e=>e.code===code);}
async function isPrivate(d,index=0){const [m]=await bucket.file(d.paths[index]).getMetadata();return !Object.hasOwn(m.metadata||{},'firebaseStorageDownloadTokens');}
async function linked(d){const content={rating:4,title:'Title',comment:'Comment',userName:'Original profile',userAvatar:'https://fixture.invalid/avatar'};await core.freezePhotoContent(db,d.actor,d.id,content,NOW);const s=await core.inspectPhotoPublication(db,d.actor,d.id,()=>NOW);await core.preparePhotoAccessPlan(db,d.actor,d.id,B,s.uploads,()=>NOW);await core.publishPhotoDraft(db,d.actor,d.id,content,NOW);}
function transactionHook(d,hook){return {collection:db.collection.bind(db),async runTransaction(fn){const result=await db.runTransaction(fn);if((await record(d).get()).data().state==='ready')await hook();return result;}};}
async function run(){
 env=await initializeTestEnvironment({projectId:P,firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(path.join(__dirname,'../../firestore.rules'),'utf8')}});
 await check('actual private upload then authoritative profile publication and unlock',async()=>{const d=await draft();assert.equal(await isPrivate(d),true);const result=await publish(db,bucket,B,request(d),()=>NOW);assert.equal(result.photoActivationState,'complete');assert.equal(Object.keys(result).sort().join(','),'photoActivationState,reviewId,state,stillCurrent');const r=(await review(d).get()).data(),s=(await record(d).get()).data();assert.equal(r.userName,'Original profile');assert.equal(r.userAvatar,'https://fixture.invalid/avatar');assert.equal(r.photoActivationState,'complete');assert.equal(s.photoActivationState,'complete');assert.equal(s.state,'linked');assert.equal(await isPrivate(d),false);});
 await check('actual capability patch only after linked pending rows and private URL denial',async()=>{const d=await draft();let observed=false;const b=adapt(async(f,m,o)=>{const s=(await record(d).get()).data(),r=(await review(d).get()).data();assert.equal(s.state,'linked');assert.equal(s.photoActivationState,'pending');assert.equal(r.photoActivationState,'pending');const a=s.photoAccessPlan.assets[0];const response=await fetch('http://127.0.0.1:9199/v0/b/'+encodeURIComponent(B)+'/o/'+encodeURIComponent(a.path)+'?alt=media&token='+encodeURIComponent(a.capability));assert.equal(response.status===200,false);observed=true;return f.setMetadata(m,o);});await publish(db,b,B,request(d),()=>NOW);assert.equal(observed,true);const a=(await record(d).get()).data().photoAccessPlan.assets[0];const response=await fetch('http://127.0.0.1:9199/v0/b/'+encodeURIComponent(B)+'/o/'+encodeURIComponent(a.path)+'?alt=media&token='+encodeURIComponent(a.capability));assert.equal(response.status,200);const bytes=Buffer.from(await response.arrayBuffer());assert.equal(hash(bytes)===a.normalizedDigest,true);});
 await check('actual SDK PATCH sends current generation and metadata conditions',async()=>{const d=await draft();let observed=false;const b=adapt(async(f,m,o,p,opts)=>{const [meta]=await f.getMetadata();assert.equal(opts.preconditionOpts.ifGenerationMatch===meta.generation,true);assert.equal(o.ifMetagenerationMatch===meta.metageneration,true);const raw=f.request_.bind(f);f.request_=(req,callback)=>{if(req.method==='PATCH'){observed=true;assert.equal(req.qs.ifGenerationMatch===meta.generation,true);assert.equal(req.qs.ifMetagenerationMatch===meta.metageneration,true);assert.equal(req.qs.generation,undefined);}return raw(req,callback);};return f.setMetadata(m,o);});await publish(db,b,B,request(d),()=>NOW);assert.equal(observed,true);});
 await check('same completed submission retry does not rotate or patch access',async()=>{const d=await draft();await publish(db,bucket,B,request(d),()=>NOW);const [first]=await bucket.file(d.paths[0]).getMetadata(),s=(await record(d).get()).data();let patches=0;const b=adapt(async()=>{patches++;throw {code:503};});assert.equal((await publish(db,b,B,request(d),()=>END)).photoActivationState,'complete');const [again]=await bucket.file(d.paths[0]).getMetadata();assert.equal(patches,0);assert.equal(again.generation===first.generation,true);assert.equal(again.metageneration===first.metageneration,true);assert.equal(JSON.stringify((await record(d).get()).data().photoAccessPlan)===JSON.stringify(s.photoAccessPlan),true);});
 await check('completed retry after later author text edit never overwrites it',async()=>{const d=await draft();await publish(db,bucket,B,request(d),()=>NOW);await assertSucceeds(updateDoc(client(d),{comment:'Later edit'}));await publish(db,bucket,B,request(d),()=>END);assert.equal((await review(d).get()).data().comment,'Later edit');});
 await check('unauthenticated refuses before object access',async()=>{const d=await draft(),b=adapt();const r=request(d);delete r.auth;await denied(publish(db,b,B,r,()=>NOW),'unauthenticated');assert.equal(b.calls.length,0);});
 await check('foreign actor refuses before object access',async()=>{const d=await draft(),b=adapt(),r=request(d);r.auth.uid='foreign';await denied(publish(db,b,B,r,()=>NOW),'permission-denied');assert.equal(b.calls.length,0);});
 for(const key of ['owner','userName','userAvatar','path','bucket','generation','capability','url'])await check('client '+key+' injection refuses',async()=>{const d=await draft(),b=adapt(),r=request(d);r.data[key]='forged';await denied(publish(db,b,B,r,()=>NOW),'invalid-argument');assert.equal(b.calls.length,0);});
 await check('wrong configured bucket refuses before object access',async()=>{const d=await draft(),b=adapt();await denied(publish(db,b,'foreign',request(d),()=>NOW),'failed-precondition');assert.equal(b.calls.length,0);});
 await check('incomplete upload batch cannot plan or publish',async()=>{const d=await draft(['one','two'],false);await upload(db,bucket,B,{auth:{uid:d.actor},data:{draftId:d.id,assetId:'one',imageBase64:image.toString('base64')}},()=>NOW);await denied(publish(db,bucket,B,request(d),()=>NOW),'failed-precondition');assert.equal((await review(d).get()).exists,false);assert.equal((await record(d).get()).data().photoAccessPlan,undefined);});
 await check('missing first authoritative profile refuses before link',async()=>{const d=await draft();await db.doc('users/'+d.actor).delete();await denied(publish(db,bucket,B,request(d),()=>NOW),'failed-precondition');assert.equal(await isPrivate(d),true);assert.equal((await review(d).get()).exists,false);});
 await check('invalid profile refuses without access capability',async()=>{const d=await draft();await db.doc('users/'+d.actor).update({photoUrl:7});await denied(publish(db,bucket,B,request(d),()=>NOW),'failed-precondition');assert.equal(await isPrivate(d),true);});
 await check('malformed rating refuses without freezing or publishing',async()=>{const d=await draft(),r=request(d);r.data.rating=2.5;await denied(publish(db,bucket,B,r,()=>NOW),'invalid-argument');assert.equal((await record(d).get()).data().publication,undefined);});
 await check('matching forged metadata does not hide wrong uploaded bytes',async()=>{const d=await draft();const [old]=await bucket.file(d.paths[0]).getMetadata();await bucket.file(d.paths[0]).save(Buffer.from('wrong bytes'),{resumable:false,metadata:{contentType:'image/jpeg',metadata:old.metadata}});const [m]=await bucket.file(d.paths[0]).getMetadata(),s=(await record(d).get()).data();const key=hash(Buffer.from(d.paths[0]));await record(d).update({uploads:{...s.uploads,[key]:{...s.uploads[key],generation:m.generation}}});await denied(publish(db,bucket,B,request(d),()=>NOW),'failed-precondition');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);});
 await check('token-bearing private draft refuses before publication',async()=>{const d=await draft();await bucket.file(d.paths[0]).setMetadata({metadata:{firebaseStorageDownloadTokens:randomUUID()}});await denied(publish(db,bucket,B,request(d),()=>NOW),'failed-precondition');assert.equal((await review(d).get()).exists,false);});
 await check('lost PATCH response recovers exact committed capability',async()=>{const d=await draft();let calls=0;const b=adapt(async(f,m,o)=>{calls++;await f.setMetadata(m,o);throw {code:503};});assert.equal((await publish(db,b,B,request(d),()=>NOW)).photoActivationState,'complete');assert.equal(calls,1);});
 await check('PATCH refusal retains linked pending review and private object',async()=>{const d=await draft(),b=adapt(async()=>{throw {code:503};});await denied(publish(db,b,B,request(d),()=>NOW),'unavailable');assert.equal((await record(d).get()).data().state,'linked');assert.equal((await review(d).get()).data().photoActivationState,'pending');assert.equal(await isPrivate(d),true);await assertFails(updateDoc(client(d),{comment:'Unsafe edit'}));assert.equal((await core.claimPhotoCleanup(db,d.actor,d.id,true,END)).claimed,false);});
 await check('retry after profile change retains original snapshot',async()=>{const d=await draft(),b=adapt(async()=>{throw {code:503};});await denied(publish(db,b,B,request(d),()=>NOW),'unavailable');await db.doc('users/'+d.actor).update({name:'Changed profile',photoUrl:'https://fixture.invalid/new-avatar'});await publish(db,bucket,B,request(d),()=>END);assert.equal((await review(d).get()).data().userName,'Original profile');assert.equal((await review(d).get()).data().userAvatar,'https://fixture.invalid/avatar');});
 await check('linked recovery does not require still-existing profile',async()=>{const d=await draft();await denied(publish(db,adapt(async()=>{throw {code:503};}),B,request(d),()=>NOW),'unavailable');await db.doc('users/'+d.actor).delete();assert.equal((await publish(db,bucket,B,request(d),()=>END)).photoActivationState,'complete');});
 await check('changed intent cannot recover by overwriting linked content',async()=>{const d=await draft();await denied(publish(db,adapt(async()=>{throw {code:503};}),B,request(d),()=>NOW),'unavailable');const r=request(d);r.data.comment='Different';await denied(publish(db,bucket,B,r,()=>END),'already-exists');assert.equal(await isPrivate(d),true);assert.equal((await review(d).get()).data().comment,'Comment');});
 await check('partial multi-photo activation retries only inactive objects',async()=>{const d=await draft(['one','two']);let patches=0;const b=adapt(async(f,m,o,p)=>{patches++;if(p===d.paths[1])throw {code:503};return f.setMetadata(m,o);});await denied(publish(db,b,B,request(d),()=>NOW),'unavailable');assert.equal(patches,2);assert.equal(await isPrivate(d,0),false);assert.equal(await isPrivate(d,1),true);const [first]=await bucket.file(d.paths[0]).getMetadata();let repairs=0;await publish(db,adapt(async(f,m,o)=>{repairs++;return f.setMetadata(m,o);}),B,request(d),()=>END);assert.equal(repairs,1);const [again]=await bucket.file(d.paths[0]).getMetadata();assert.equal(first.metageneration===again.metageneration,true);assert.equal((await record(d).get()).data().photoActivationState,'complete');});
 await check('expired unlinked submission stays private',async()=>{const d=await draft();await denied(publish(db,bucket,B,request(d),()=>END),'deadline-exceeded');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);});
 await check('expiry crossing verified bytes refuses readiness',async()=>{const d=await draft();let now=NOW;const b=adapt(null,async(result)=>{now=END;return result;});await denied(publish(db,b,B,request(d),()=>now),'deadline-exceeded');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);});
 await check('expiry after readiness refuses first link without issuing capability',async()=>{const d=await draft();let now=NOW;const hooked=transactionHook(d,async()=>{now=END;});await denied(publish(hooked,bucket,B,request(d),()=>now),'deadline-exceeded');assert.equal((await record(d).get()).data().state,'ready');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);});
 await check('expiry during linked activation still permits safe completion',async()=>{const d=await draft();let now=NOW;const b=adapt(async(f,m,o)=>{now=END;return f.setMetadata(m,o);});assert.equal((await publish(db,b,B,request(d),()=>now)).photoActivationState,'complete');});
 await check('cleanup during verification prevents planning and any link',async()=>{const d=await draft();let claimed=false;const b=adapt(null,async(result)=>{if(!claimed){claimed=true;await core.claimPhotoCleanup(db,d.actor,d.id,true,NOW);}return result;});await denied(publish(db,b,B,request(d),()=>NOW),'failed-precondition');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);});
 await check('product deleted before first link is not published',async()=>{const d=await draft();let removed=false;const b=adapt(null,async(result)=>{if(!removed){removed=true;await db.doc('products/p').delete();}return result;});await denied(publish(db,b,B,request(d),()=>NOW),'not-found');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);});
 await check('foreign review ownership at first link refuses capability',async()=>{const d=await draft();let changed=false;const hooked=transactionHook(d,async()=>{if(!changed){changed=true;await review(d).set({userId:'foreign',productId:'p',rating:4});}});await denied(publish(hooked,bucket,B,request(d),()=>NOW),'permission-denied');assert.equal(await isPrivate(d),true);});
 await check('replacement after private verification cannot receive old planned access',async()=>{const d=await draft();let changed=false,reads=0;const b=adapt(null,async(result,p,opts)=>{if(!opts&&++reads===2&&!changed){changed=true;await bucket.file(p).save(image,{resumable:false,metadata:{contentType:'image/jpeg',metadata:result[0].metadata}});}return result;});await denied(publish(db,b,B,request(d),()=>NOW),'failed-precondition');assert.equal(await isPrivate(d),true);assert.equal((await review(d).get()).data().photoActivationState,'pending');});
 await check('metadata precondition double prevents stale patch then repairs on retry',async()=>{const d=await draft();const b=adapt(async(f,m,o)=>{await f.setMetadata({metadata:{safeFixture:'changed'}});const [current]=await f.getMetadata();if(o.ifMetagenerationMatch===current.metageneration) return f.setMetadata(m,o);if(o.ifMetagenerationMatch)throw {code:412};return f.setMetadata(m,o);});await denied(publish(db,b,B,request(d),()=>NOW),'unavailable');assert.equal(await isPrivate(d),true);assert.equal((await review(d).get()).data().photoActivationState,'pending');assert.equal((await publish(db,bucket,B,request(d),()=>END)).photoActivationState,'complete');});
 await check('generation precondition double never activates replacement',async()=>{const d=await draft();const b=adapt(async(f,m,o)=>{await f.save(image,{resumable:false,metadata:{contentType:'image/jpeg',metadata:{reviewPhotoInputDigest:m.metadata.reviewPhotoInputDigest,reviewPhotoNormalizedDigest:m.metadata.reviewPhotoNormalizedDigest}}});const [current]=await f.getMetadata();if(o.ifGenerationMatch&&o.ifGenerationMatch!==current.generation)throw {code:412};return f.setMetadata(m,o);});await denied(publish(db,b,B,request(d),()=>NOW),'failed-precondition');assert.equal(await isPrivate(d),true);await denied(publish(db,bucket,B,request(d),()=>END),'failed-precondition');assert.equal(await isPrivate(d),true);});
 await check('conflicting capability is never overwritten by recovery',async()=>{const d=await draft();await linked(d);const other=randomUUID();await bucket.file(d.paths[0]).setMetadata({metadata:{firebaseStorageDownloadTokens:other}});let patches=0;await denied(publish(db,adapt(async()=>{patches++;}),B,request(d),()=>END),'failed-precondition');assert.equal(patches,0);const [m]=await bucket.file(d.paths[0]).getMetadata();assert.equal(m.metadata.firebaseStorageDownloadTokens===other,true);});
 await check('changed plan receipts fail before any Storage capability patch',async()=>{const d=await draft();await linked(d);const s=(await record(d).get()).data();await record(d).update({receipts:[{...s.receipts[0],url:'https://fixture.invalid/forged'}]});const b=adapt();await denied(publish(db,b,B,request(d),()=>END),'failed-precondition');assert.equal(b.calls.length,0);assert.equal(await isPrivate(d),true);});
 await check('deleted linked review is not recreated or activated',async()=>{const d=await draft();await linked(d);await review(d).delete();const b=adapt();const r=await publish(db,b,B,request(d),()=>END);assert.equal(r.stillCurrent,false);assert.equal(r.photoActivationState,'superseded');assert.equal(b.calls.length,0);assert.equal(await isPrivate(d),true);});
 await check('changed linked content refuses all capability access',async()=>{const d=await draft();await linked(d);await review(d).update({comment:'Privileged later change'});const b=adapt();await denied(publish(db,b,B,request(d),()=>END),'failed-precondition');assert.equal(b.calls.length,0);assert.equal(await isPrivate(d),true);});
 await check('voting during activation preserved when both locks complete',async()=>{const d=await draft();const b=adapt(async(f,m,o)=>{const actor='voter',r=doc(env.authenticatedContext(actor).firestore(),'products/p/reviews/'+d.actor);await assertSucceeds(updateDoc(r,{helpfulUsers:[actor],helpfulCount:1}));return f.setMetadata(m,o);});await publish(db,b,B,request(d),()=>NOW);assert.equal((await review(d).get()).data().helpfulCount,1);assert.equal((await review(d).get()).data().photoActivationState,'complete');await assertSucceeds(updateDoc(client(d),{comment:'Completed edit'}));});
 await check('revoked earlier partial capability prevents premature completion',async()=>{const d=await draft(['one','two']);const b=adapt(async(f,m,o,p)=>{const r=await f.setMetadata(m,o);if(p===d.paths[1])await bucket.file(d.paths[0]).setMetadata({metadata:{firebaseStorageDownloadTokens:randomUUID()}});return r;});await denied(publish(db,b,B,request(d),()=>NOW),'failed-precondition');assert.equal((await record(d).get()).data().photoActivationState,'pending');assert.equal((await review(d).get()).data().photoActivationState,'pending');});
 await check('privileged review removal during patch retains recovery lock',async()=>{const d=await draft();const b=adapt(async(f,m,o)=>{const r=await f.setMetadata(m,o);await review(d).delete();return r;});await denied(publish(db,b,B,request(d),()=>NOW),'failed-precondition');assert.equal((await record(d).get()).data().photoActivationState,'pending');assert.equal((await review(d).get()).exists,false);});
 await check('concurrent submission retries use one stable plan and completion',async()=>{const d=await draft();const results=await Promise.allSettled([publish(db,bucket,B,request(d),()=>NOW),publish(db,bucket,B,request(d),()=>NOW)]);assert.equal(results.some(r=>r.status==='fulfilled'&&r.value.photoActivationState==='complete'),true);assert.equal((await record(d).get()).data().photoActivationState,'complete');assert.equal((await publish(db,bucket,B,request(d),()=>END)).photoActivationState,'complete');});
 await check('lost readiness transaction response reuses durable private plan',async()=>{const d=await draft();let lost=false;const hooked=transactionHook(d,async()=>{if(!lost){lost=true;throw {code:503};}});await denied(publish(hooked,bucket,B,request(d),()=>NOW),'unavailable');const first=(await record(d).get()).data().photoAccessPlan;assert.equal((await record(d).get()).data().state,'ready');assert.equal((await review(d).get()).exists,false);assert.equal(await isPrivate(d),true);await publish(db,bucket,B,request(d),()=>NOW);assert.equal(JSON.stringify((await record(d).get()).data().photoAccessPlan)===JSON.stringify(first),true);});
 await check('lost link transaction response retries without premature capability',async()=>{const d=await draft();let lost=false;const hooked={collection:db.collection.bind(db),async runTransaction(fn){const r=await db.runTransaction(fn),s=(await record(d).get()).data();if(s.state==='linked'&&s.photoActivationState==='pending'&&!lost){lost=true;throw {code:503};}return r;}};await denied(publish(hooked,bucket,B,request(d),()=>NOW),'unavailable');assert.equal((await record(d).get()).data().state,'linked');assert.equal(await isPrivate(d),true);assert.equal((await publish(db,bucket,B,request(d),()=>END)).photoActivationState,'complete');});
 await check('lost completion transaction response uses completed receipt without patch',async()=>{const d=await draft();let lost=false;const hooked={collection:db.collection.bind(db),async runTransaction(fn){const r=await db.runTransaction(fn),s=(await record(d).get()).data();if(s.photoActivationState==='complete'&&!lost){lost=true;throw {code:503};}return r;}};await denied(publish(hooked,bucket,B,request(d),()=>NOW),'unavailable');assert.equal((await review(d).get()).data().photoActivationState,'complete');let patches=0;const b=adapt(async()=>{patches++;throw {code:503};});assert.equal((await publish(db,b,B,request(d),()=>END)).photoActivationState,'complete');assert.equal(patches,0);});
 await check('ready plan with newly token-bearing object fails before first link',async()=>{const d=await draft();let lost=false;await denied(publish(transactionHook(d,async()=>{if(!lost){lost=true;throw {code:503};}}),bucket,B,request(d),()=>NOW),'unavailable');await bucket.file(d.paths[0]).setMetadata({metadata:{firebaseStorageDownloadTokens:randomUUID()}});await denied(publish(db,bucket,B,request(d),()=>NOW),'failed-precondition');assert.equal((await review(d).get()).exists,false);});
 await check('durable access plan missing frozen submission fails closed',async()=>{const d=await draft();await linked(d);await record(d).update({publication:admin.firestore.FieldValue.delete()});const b=adapt();await denied(publish(db,b,B,request(d),()=>END),'failed-precondition');assert.equal(b.calls.length,0);assert.equal(await isPrivate(d),true);});
 await check('draft-only forged completion does not release pending review',async()=>{const d=await draft();await linked(d);await record(d).update({photoActivationState:'complete'});const b=adapt();await denied(publish(db,b,B,request(d),()=>END),'failed-precondition');assert.equal(b.calls.length,0);assert.equal((await review(d).get()).data().photoActivationState,'pending');assert.equal(await isPrivate(d),true);});
 await check('unlinked readiness cannot pass trusted activation boundary',async()=>{const d=await draft();const c={rating:4,title:'Title',comment:'Comment',userName:'Original profile',userAvatar:'https://fixture.invalid/avatar'};await core.freezePhotoContent(db,d.actor,d.id,c,NOW);const inspected=await core.inspectPhotoPublication(db,d.actor,d.id,()=>NOW);const plan=await core.preparePhotoAccessPlan(db,d.actor,d.id,B,inspected.uploads,()=>NOW);const s=(await record(d).get()).data();await record(d).update({photoActivationState:'pending',contentHash:s.publication.contentHash});await review(d).set({...c,userId:d.actor,productId:'p',photoDraftId:d.id,photoActivationState:'pending',imageUrls:plan.assets.map(a=>a.url)});await denied(core.inspectPhotoActivation(db,d.actor,d.id,B),'failed-precondition');assert.equal(await isPrivate(d),true);});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Unexpected fixture failure: '+(e.code||e.name));process.exitCode=1;}).finally(async()=>{if(env)await env.cleanup();await app.delete();});
