// Actual demo Auth/Firestore/Storage + v1 HTTP. Handler simulations explicitly model
// an SDK-verified identity captured before an account lifecycle change.
const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
for(const key of ['FIRESTORE_EMULATOR_HOST','FIREBASE_AUTH_EMULATOR_HOST','FIREBASE_STORAGE_EMULATOR_HOST'])if(!/^(127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(process.env[key]||''))throw Error('Loopback emulators required.');
const P='demo-agrimore-account-recovery';process.env.GCLOUD_PROJECT=P;process.env.STORAGE_EMULATOR_HOST='http://'+process.env.FIREBASE_STORAGE_EMULATOR_HOST;
const admin=require('firebase-admin'),express=require('express');
const app=admin.initializeApp({projectId:P,storageBucket:P+'.appspot.com'}),db=app.firestore(),auth=app.auth();
const remove=require('../lib/customer/deleteUserData').deleteUserData;
let sequence=0,passed=0,failed=0,server;
async function fixture(balance=0){
 const uid='recovery'+(++sequence),email=uid+'@fixture.invalid',password=randomUUID();await auth.createUser({uid,email,password});
 await db.doc('users/'+uid).set({name:'Private fixture',role:'user'});await db.doc('wallets/'+uid).set({userId:uid,balance});
 const r=await fetch('http://'+process.env.FIREBASE_AUTH_EMULATOR_HOST+'/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})}),d=await r.json();
 if(r.status!==200||typeof d.idToken!=='string')throw Error('Synthetic sign-in failed.');return {uid,jwt:d.idToken,token:await auth.verifyIdToken(d.idToken)};
}
const invoke=(u,data={expectedOwnerId:u.uid},token=u.token)=>remove.run(data,{auth:{uid:u.uid,token,rawToken:u.jwt}});
async function http(u,data={expectedOwnerId:u.uid}){const r=await fetch('http://127.0.0.1:9973/deleteUserData',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+u.jwt},body:JSON.stringify({data})});const b=await r.json();return {error:b.error?.status,result:b.result};}
async function kept(u){assert.equal((await db.doc('users/'+u.uid).get()).exists,true);assert.equal((await db.doc('wallets/'+u.uid).get()).exists,true);assert.equal((await db.doc('account_deletion_audit/'+u.uid).get()).exists,false);}
async function gone(u){assert.equal((await db.doc('users/'+u.uid).get()).exists,false);assert.equal((await db.doc('wallets/'+u.uid).get()).exists,false);assert.equal((await db.doc('account_deletion_audit/'+u.uid).get()).exists,true);await assert.rejects(()=>auth.getUser(u.uid),e=>e.code==='auth/user-not-found');}
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function failBatch(path,body){const original=db.batch;db.batch=function(){const b=original.call(db),commit=b.commit.bind(b),update=b.update.bind(b),del=b.delete.bind(b);let hit=false;b.update=function(r,...args){hit ||= r.path===path;return update(r,...args);};b.delete=function(r,...args){hit ||= r.path===path;return del(r,...args);};b.commit=async function(){if(hit)throw Error('Synthetic batch failure');return commit();};return b;};try{await body();}finally{db.batch=original;}}
async function failDocument(path,method,lostResponse,body){const proto=Object.getPrototypeOf(db.doc(path)),original=proto[method];proto[method]=async function(...args){if(this.path===path){if(lostResponse)await original.apply(this,args);throw Error('Synthetic document failure');}return original.apply(this,args);};try{await body();}finally{proto[method]=original;}}
async function run(){
 const web=express();web.use(express.json());web.post('/deleteUserData',remove);server=await new Promise(resolve=>{const s=web.listen(9973,'127.0.0.1',()=>resolve(s));});
 for(const kind of ['disabled','revoked','deleted'])await check(kind+' preverified handler context denied before deletion',async()=>{const u=await fixture();if(kind==='disabled')await auth.updateUser(u.uid,{disabled:true});if(kind==='revoked'){await new Promise(resolve=>setTimeout(resolve,1100));await auth.revokeRefreshTokens(u.uid);}if(kind==='deleted')await auth.deleteUser(u.uid);await assert.rejects(()=>invoke(u),e=>e.code==='unauthenticated');await kept(u);assert.equal((await http(u)).error,'UNAUTHENTICATED');});
 for(const value of [undefined,null,'0',-1,0.5,NaN])await check('invalid auth_time '+String(value)+' denied',async()=>{const u=await fixture(5);await assert.rejects(()=>invoke(u,undefined,{...u.token,auth_time:value}),e=>e.code==='unauthenticated');await kept(u);});
 await check('Auth lookup failure denies without deletion',async()=>{const u=await fixture(),original=auth.getUser;auth.getUser=async()=>{throw Error('Synthetic Auth outage');};try{await assert.rejects(()=>invoke(u),e=>e.code==='unauthenticated');}finally{auth.getUser=original;}await kept(u);});
 for(const [name,change] of [['mismatched identity',{uid:'different'}],['corrupt revocation date',{tokensValidAfterTime:'invalid'}]])await check(name+' metadata denied',async()=>{const u=await fixture(),original=auth.getUser;auth.getUser=async()=>({...await original.call(auth,u.uid),...change});try{await assert.rejects(()=>invoke(u),e=>e.code==='unauthenticated');}finally{auth.getUser=original;}await kept(u);});
 await check('fresh HTTP deletion preserves foreign account and accounting history',async()=>{const u=await fixture(),other=await fixture();await db.doc('orders/'+u.uid).set({userId:u.uid,orderStatus:'delivered',total:9,deliveryAddress:{name:'Private fixture'},notes:'Private'});await db.doc('wallet_transactions/'+u.uid).set({userId:u.uid,amount:9});const r=await http(u);assert.equal(r.error,undefined);assert.equal(r.result.success,true);await gone(u);const order=(await db.doc('orders/'+u.uid).get()).data();assert.equal(order.deliveryAddress,null);assert.equal(order.notes,'');assert.equal(order.total,9);assert.equal((await db.doc('wallet_transactions/'+u.uid).get()).data().amount,9);await kept(other);});
 await check('active-session wallet refusal remains unchanged',async()=>{const u=await fixture(5);await assert.rejects(()=>invoke(u),e=>e.code==='failed-precondition');await kept(u);});
 await check('owner hint denied before Auth lookup',async()=>{const u=await fixture(),original=auth.getUser;auth.getUser=async()=>{throw Error('Auth must not be touched');};try{await assert.rejects(()=>invoke(u,{expectedOwnerId:'foreign'}),e=>e.code==='permission-denied');}finally{auth.getUser=original;}await kept(u);});
 await check('review query failure retains profile and Auth for safe retry',async()=>{const u=await fixture();await db.doc('products/recovery/reviews/'+u.uid).set({userId:u.uid,userName:'Private',userAvatar:'Private',createdAt:admin.firestore.Timestamp.now()});const original=db.collectionGroup;db.collectionGroup=function(name){if(name==='reviews')throw Error('Synthetic review index outage');return original.call(db,name);};try{await assert.rejects(()=>invoke(u),e=>e.code==='failed-precondition');await kept(u);assert.equal((await auth.getUser(u.uid)).uid,u.uid);}finally{db.collectionGroup=original;}assert.equal((await invoke(u)).success,true);assert.equal((await db.doc('products/recovery/reviews/'+u.uid).get()).data().userName,'Deleted user');await gone(u);});
 await check('seller KYC delete failure retains role marker and cleans owned files on retry',async()=>{const u=await fixture(),other=await fixture(),bucket=app.storage().bucket();await db.doc('sellers/'+u.uid).set({status:'approved'});const owned=bucket.file('seller_documents/'+u.uid+'/fixture.jpg'),foreign=bucket.file('seller_documents/'+other.uid+'/fixture.jpg');await owned.save(Buffer.from('Synthetic'),{resumable:false});await foreign.save(Buffer.from('Foreign synthetic'),{resumable:false});const proto=Object.getPrototypeOf(owned),original=proto.delete;proto.delete=async function(...args){if(this.name===owned.name)throw Error('Synthetic KYC delete outage');return original.apply(this,args);};try{await assert.rejects(()=>invoke(u));assert.equal((await db.doc('sellers/'+u.uid).get()).exists,true);assert.equal((await db.doc('users/'+u.uid).get()).exists,true);assert.equal((await owned.exists())[0],true);}finally{proto.delete=original;}assert.equal((await invoke(u)).success,true);assert.equal((await owned.exists())[0],false);assert.equal((await foreign.exists())[0],true);assert.equal((await db.doc('account_deletion_audit/'+u.uid).get()).data().wasSeller,true);await gone(u);await kept(other);});
 await check('order anonymization failure retains marker and retries all work',async()=>{const u=await fixture(),p='orders/'+u.uid;await db.doc(p).set({userId:u.uid,orderStatus:'delivered',deliveryAddress:{name:'Private'},notes:'Private'});await failBatch(p,async()=>{await assert.rejects(()=>invoke(u));assert.equal((await db.doc('users/'+u.uid).get()).exists,true);});assert.equal((await invoke(u)).success,true);assert.equal((await db.doc(p).get()).data().deliveryAddress,null);await gone(u);});
 await check('personal batch failure retains marker and retries',async()=>{const u=await fixture();await failBatch('wallets/'+u.uid,async()=>{await assert.rejects(()=>invoke(u));assert.equal((await db.doc('users/'+u.uid).get()).exists,true);});assert.equal((await invoke(u)).success,true);await gone(u);});
 for(const lost of [false,true])await check('audit '+(lost?'lost response':'write failure')+' retains marker and retries',async()=>{const u=await fixture();await failDocument('account_deletion_audit/'+u.uid,'set',lost,async()=>{await assert.rejects(()=>invoke(u));assert.equal((await db.doc('users/'+u.uid).get()).exists,true);assert.equal((await auth.getUser(u.uid)).uid,u.uid);});assert.equal((await invoke(u)).success,true);await gone(u);});
 for(const lost of [false,true])await check('last profile marker '+(lost?'lost response':'failure')+' has durable audit and retries Auth',async()=>{const u=await fixture();await failDocument('users/'+u.uid,'delete',lost,async()=>{await assert.rejects(()=>invoke(u));assert.equal((await db.doc('account_deletion_audit/'+u.uid).get()).exists,true);assert.equal((await db.doc('users/'+u.uid).get()).exists,!lost);});assert.equal((await invoke(u)).success,true);await gone(u);});
 await check('missing legacy profile without audit repeats personal sweep',async()=>{const u=await fixture();await db.doc('users/'+u.uid).delete();await db.doc('orders/'+u.uid).set({userId:u.uid,orderStatus:'delivered',deliveryAddress:{name:'Private'},notes:'Private'});await db.doc('addresses/'+u.uid).set({userId:u.uid,name:'Private'});assert.equal((await invoke(u)).success,true);assert.equal((await db.doc('addresses/'+u.uid).get()).exists,false);assert.equal((await db.doc('orders/'+u.uid).get()).data().deliveryAddress,null);await gone(u);});
 await check('legacy incomplete review audit reruns personal sweep with active Auth',async()=>{const u=await fixture();await db.doc('users/'+u.uid).delete();await db.doc('account_deletion_audit/'+u.uid).set({uid:u.uid,deletedAt:admin.firestore.Timestamp.now(),anonymizedReviewsCount:-1});await db.doc('products/recovery/reviews/'+u.uid).set({userId:u.uid,userName:'Private',userAvatar:'Private',createdAt:admin.firestore.Timestamp.now()});assert.equal((await invoke(u)).success,true);assert.equal((await db.doc('products/recovery/reviews/'+u.uid).get()).data().userName,'Deleted user');await gone(u);});
 await check('later child-delete batch failure retains final marker and retries remaining children',async()=>{const u=await fixture();for(let start=0;start<455;start+=400){const b=db.batch();for(let i=start;i<Math.min(start+400,455);i++)b.set(db.doc('users/'+u.uid+'/notifications/item'+String(i).padStart(3,'0')),{private:'Fixture'});await b.commit();}const p='users/'+u.uid+'/notifications/item454';await failBatch(p,async()=>{await assert.rejects(()=>invoke(u));assert.equal((await db.doc('users/'+u.uid).get()).exists,true);assert.equal((await db.doc(p).get()).exists,true);});assert.equal((await invoke(u)).success,true);assert.equal((await db.collection('users').doc(u.uid).collection('notifications').get()).size,0);await gone(u);});
 await check('Auth deletion failure recovers after complete Firestore deletion',async()=>{const u=await fixture(),original=auth.deleteUser;auth.deleteUser=async()=>{throw Error('Synthetic Auth deletion failure');};try{await assert.rejects(()=>invoke(u),e=>e.code==='internal');assert.equal((await db.doc('users/'+u.uid).get()).exists,false);assert.equal((await db.doc('account_deletion_audit/'+u.uid).get()).exists,true);}finally{auth.deleteUser=original;}const r=await invoke(u);assert.equal(r.alreadyDeleted,true);await gone(u);});
 await check('completed deleted principal receives only read-only own receipt',async()=>{const u=await fixture();await invoke(u);const batch=db.batch,del=auth.deleteUser;db.batch=()=>{throw Error('Receipt attempted mutation');};auth.deleteUser=async()=>{throw Error('Receipt attempted Auth deletion');};try{const r=await invoke(u);assert.equal(r.success,true);assert.equal(r.alreadyDeleted,true);assert.equal(r.hardDeletedDocCount,0);}finally{db.batch=batch;auth.deleteUser=del;}await gone(u);});
 await check('legitimate sub-millisecond Firestore audit timestamp retains read-only receipt',async()=>{const u=await fixture();await invoke(u);const ref=db.doc('account_deletion_audit/'+u.uid),ts=(await ref.get()).data().deletedAt,nanos=ts.nanoseconds+1000;await ref.update({deletedAt:new admin.firestore.Timestamp(ts.seconds+Math.floor(nanos/1e9),nanos%1e9)});const r=await invoke(u);assert.equal(r.alreadyDeleted,true);assert.equal(r.hardDeletedDocCount,0);await gone(u);});
 for(const kind of ['missing','wrong-owner','bad-time','old-time','profile-present','review-incomplete'])await check('deleted principal rejects '+kind+' completion evidence',async()=>{const u=await fixture(5);await auth.deleteUser(u.uid);if(kind!=='profile-present')await db.doc('users/'+u.uid).delete();if(kind!=='missing')await db.doc('account_deletion_audit/'+u.uid).set({uid:kind==='wrong-owner'?'foreign':u.uid,anonymizedReviewsCount:kind==='review-incomplete'?-1:0,deletedAt:kind==='bad-time'?'invalid':admin.firestore.Timestamp.fromMillis(kind==='old-time'?0:Date.now())});await assert.rejects(()=>invoke(u),e=>e.code==='unauthenticated');assert.equal((await db.doc('wallets/'+u.uid).get()).data().balance,5);});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Fixture failure: '+e.name+' '+e.message);process.exitCode=1;}).finally(async()=>{if(server)await new Promise(resolve=>server.close(resolve));await app.delete();});
