// Real local onCall SDK HTTP protocol + Auth/Firestore/Storage emulators.
// App Check verification/consumption is an explicit test double, never a live attestation claim.
process.env.GCLOUD_PROJECT='demo-agrimore-photo-rpc';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.STORAGE_EMULATOR_HOST='http://127.0.0.1:9199';
delete process.env.REVIEW_PHOTO_FLOW_ENABLED;delete process.env.REVIEW_PHOTO_APPCHECK_REQUIRED;
const admin=require('firebase-admin'),express=require('express'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),jpeg=require('jpeg-js'),{randomUUID,createHash}=require('crypto');
const {getAppCheck}=require('firebase-admin/app-check'),{initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc,deleteDoc}=require('firebase/firestore');
const P='demo-agrimore-photo-rpc',app=admin.initializeApp({projectId:P,storageBucket:P+'.appspot.com'}),db=app.firestore(),auth=app.auth(),bucket=app.storage().bucket(),B=bucket.name;
const proofs=new Set(),used=new Set(),verifier=getAppCheck(app);
verifier.verifyToken=async function(value,options){if(!proofs.has(value))throw Error('Synthetic attestation denied.');const receipt={appId:'demo-photo-app',token:{app_id:'demo-photo-app'}};if(options?.consume){receipt.alreadyConsumed=used.has(value);used.add(value);}return receipt;};
const rpc=require('../lib/seller/reviewPhotoRpc');
let now=Date.now(),enabled=true,approved=true,denyPatch=false,seq=0,passed=0,failed=0,server,env;
const normalized=jpeg.encode({width:1,height:1,data:Buffer.from([200,20,60,255])},90).data.toString('base64');
const deps={db:()=>db,bucket:()=>denyPatch?{name:B,file(p,o){const f=bucket.file(p,o);return {getMetadata:f.getMetadata.bind(f),download:f.download.bind(f),async setMetadata(){throw {code:503};}};}}:bucket,expectedBucket:()=>B,enabled:()=>enabled,appCheckApproved:()=>approved,now:()=>now,user:uid=>auth.getUser(uid)};
const calls=rpc.buildReviewPhotoCallables(deps,true),hash=s=>createHash('sha256').update(s).digest('hex'),quota=(u,lane='work')=>db.doc('review_photo_rpc_limits/'+hash(u.actor)+'_'+lane);
async function principal(){const actor='rpc'+(++seq),password=randomUUID(),email=actor+'@fixture.invalid';await auth.createUser({uid:actor,email,password});const res=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const data=await res.json();if(res.status!==200||typeof data.idToken!=='string')throw Error('Synthetic Auth sign-in failed.');await db.doc('users/'+actor).set({name:'Original profile',photoUrl:''});return {actor,jwt:data.idToken,authTime:JSON.parse(Buffer.from(data.idToken.split('.')[1],'base64url').toString()).auth_time};}
async function setup(){enabled=true;approved=true;denyPatch=false;now=Date.now();await db.doc('products/p').set({name:'Synthetic product'});await db.doc('review_photo_rpc_limits/global_work').delete();await db.doc('review_photo_rpc_limits/global_status').delete();return principal();}
const draftData=(u,id='draft-'+u.actor,assets=['one'])=>({draftId:id,productId:'p',reviewId:u.actor,assetIds:assets});
const fresh=()=>{const value=randomUUID();proofs.add(value);return value;};
async function invoke(name,u,data,options={}){const headers={'content-type':'application/json'};if(u)headers.authorization='Bearer '+u.jwt;if(options.proof!==null)headers['X-Firebase-AppCheck']=options.proof||fresh();const res=await fetch('http://127.0.0.1:9971/'+(options.off?'off/':'')+name,{method:'POST',headers,body:JSON.stringify({data})});const body=await res.json();return {http:res.status,result:body.result,error:body.error?.status};}
async function ok(name,u,data){const r=await invoke(name,u,data);assert.equal(r.error,undefined);assert.equal(r.http,200);safe(r.result);return r.result;}
function safe(value){const text=JSON.stringify(value);assert.equal(/"(?:[^"\\]*(?:capability|token|url|path|digest|receipt|plan|profile|avatar|userName)[^"\\]*)"\s*:/i.test(text),false);assert.equal(text.includes('https://'),false);assert.equal(text.includes('imageBase64'),false);}
async function denied(name,u,data,status,options){const r=await invoke(name,u,data,options);assert.equal(r.error,status);assert.equal(r.result,undefined);}
async function create(u,assets=['one']){const d=draftData(u,'draft-'+u.actor,assets);await ok('createReviewPhotoDraft',u,d);return d;}
async function upload(u,d,assetId='one'){return ok('uploadReviewPhotoAsset',u,{draftId:d.draftId,assetId,imageBase64:normalized});}
const publishData=d=>({draftId:d.draftId,rating:4,title:'Title',comment:'Comment'});
async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.name+' '+e.message);}}
async function run(){
 env=await initializeTestEnvironment({projectId:P,firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(path.join(__dirname,'../../firestore.rules'),'utf8')}});
 const web=express();web.use(express.json({limit:'3mb'}));for(const [name,f] of Object.entries(calls))web.post('/'+name,f);for(const [name,f] of Object.entries(rpc))if(calls[name])web.post('/off/'+name,f);server=await new Promise(resolve=>{const s=web.listen(9971,'127.0.0.1',()=>resolve(s));});
 await check('SDK v2 bounded CPU memory concurrency instances and timeout',async()=>{for(const f of Object.values(calls)){const e=f.__endpoint;assert.equal(e.platform,'gcfv2');assert.equal(e.availableMemoryMb,256);assert.equal(e.cpu,1);assert.equal(e.concurrency,1);assert.equal(e.maxInstances,1);assert.equal(e.minInstances,0);assert.equal(e.timeoutSeconds,60);}});
 await check('production defaults disabled without enforcing App Check by default',async()=>{const u=await setup();const r=await invoke('createReviewPhotoDraft',u,draftData(u),{off:true,proof:null});assert.equal(r.error,'FAILED_PRECONDITION');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);assert.equal((await db.doc('review_photo_drafts/draft-'+u.actor).get()).exists,false);});
 await check('flow disabled rejects client enablement hints without business effects',async()=>{const u=await setup();enabled=false;await denied('createReviewPhotoDraft',u,{...draftData(u),enabled:true},'FAILED_PRECONDITION');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('App Check approval gate cannot be skipped with flow enabled',async()=>{const u=await setup();approved=false;await denied('createReviewPhotoDraft',u,draftData(u),'FAILED_PRECONDITION');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('actual HTTP create upload publish status and linked cleanup',async()=>{const u=await setup(),d=await create(u);const receipt=await upload(u,d);assert.equal(Object.keys(receipt).sort().join(','),'assetId,draftId,state');const r=await ok('publishReviewPhotoDraft',u,publishData(d));assert.equal(r.photoActivationState,'complete');const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.state,'linked');assert.equal(s.stillCurrent,true);assert.equal(s.recoveryRequired,false);const c=await ok('cleanupReviewPhotoDraft',u,{draftId:d.draftId,abandon:true});assert.equal(c.cleanupClaimed,false);assert.equal(c.deletedCount,0);assert.equal(c.recoveryRequired,false);});
 await check('HTTP authentication cannot be supplied through data',async()=>{const u=await setup();await denied('createReviewPhotoDraft',null,{...draftData(u),auth:{uid:u.actor}},'UNAUTHENTICATED');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('invalid bearer authentication rejected by actual SDK',async()=>{const u=await setup();u.jwt=randomUUID();await denied('createReviewPhotoDraft',u,draftData(u),'UNAUTHENTICATED');});
 await check('missing attestation rejected by actual SDK',async()=>{const u=await setup();await denied('createReviewPhotoDraft',u,draftData(u),'UNAUTHENTICATED',{proof:null});});
 await check('invalid attestation rejected by SDK verifier boundary',async()=>{const u=await setup();await denied('createReviewPhotoDraft',u,draftData(u),'UNAUTHENTICATED',{proof:randomUUID()});});
 await check('consumed attestation rejected by handler after SDK consumption',async()=>{const u=await setup(),proof=fresh();await ok('createReviewPhotoDraft',u,draftData(u));await invoke('getReviewPhotoDraftStatus',u,{draftId:'draft-'+u.actor},{proof});const before=(await quota(u,'status').get()).data().count;await denied('getReviewPhotoDraftStatus',u,{draftId:'draft-'+u.actor},'UNAUTHENTICATED',{proof});assert.equal((await quota(u,'status').get()).data().count,before);});
 await check('disabled Auth principal cannot allocate draft with existing JWT',async()=>{const u=await setup();await auth.updateUser(u.actor,{disabled:true});await denied('createReviewPhotoDraft',u,draftData(u),'UNAUTHENTICATED');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('deleted Auth principal cannot allocate draft with existing JWT',async()=>{const u=await setup();await auth.deleteUser(u.actor);await denied('createReviewPhotoDraft',u,draftData(u),'UNAUTHENTICATED');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('revoked Auth session cannot allocate draft with earlier JWT',async()=>{const u=await setup();await new Promise(resolve=>setTimeout(resolve,1100));await auth.revokeRefreshTokens(u.actor);const p=await auth.getUser(u.actor);assert.equal(Date.parse(p.tokensValidAfterTime)>u.authTime*1000,true);await denied('createReviewPhotoDraft',u,draftData(u),'UNAUTHENTICATED');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 for(const [name,patch] of [['client owner',{owner:'foreign'}],['client path',{path:'foreign/photo.jpg'}],['client bucket',{bucket:'foreign'}],['client generation',{generation:'1'}],['client App Check',{app:{alreadyConsumed:false}}]])await check(name+' injection rejects',async()=>{const u=await setup();await denied('createReviewPhotoDraft',u,{...draftData(u),...patch},'INVALID_ARGUMENT');});
 for(const [name,change] of [['invalid draft ID',{draftId:'nested/id'}],['invalid review ID',{reviewId:''}],['duplicate assets',{assetIds:['one','one']}],['empty assets',{assetIds:[]}],['too many assets',{assetIds:Array.from({length:11},(_,i)=>'a'+i)}],['prototype asset',{assetIds:['__proto__']}],['nested asset',{assetIds:['a/b']}],['oversized identity',{productId:'x'.repeat(129)}]])await check(name+' refuses before budget',async()=>{const u=await setup();await denied('createReviewPhotoDraft',u,{...draftData(u),...change},'INVALID_ARGUMENT');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('foreign draft status denies without private response',async()=>{const u=await setup(),d=await create(u),v=await principal();await denied('getReviewPhotoDraftStatus',v,{draftId:d.draftId},'PERMISSION_DENIED');});
 await check('partial upload status returns IDs without private metadata',async()=>{const u=await setup(),d=await create(u,['one','two']);await upload(u,d);const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.uploadedAssetIds.length,1);assert.equal(s.uploadedAssetIds[0],'one');assert.equal(s.assetIds.length,2);assert.equal(s.state,'open');});
 await check('expired open status remains inspectable and creation retry cannot renew lease',async()=>{const u=await setup(),d=await create(u);const first=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});now=first.expiresAt;const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.leaseExpired,true);assert.equal(s.recoveryRequired,true);const repeated=await ok('createReviewPhotoDraft',u,d);assert.equal(repeated.expiresAt,first.expiresAt);assert.equal(repeated.leaseExpired,true);});
 await check('active cleanup requires explicit abandon',async()=>{const u=await setup(),d=await create(u);await denied('cleanupReviewPhotoDraft',u,{draftId:d.draftId,abandon:false},'FAILED_PRECONDITION');});
 await check('abandon deletes actual object but retains recovery tombstone/status',async()=>{const u=await setup(),d=await create(u);await upload(u,d);const c=await ok('cleanupReviewPhotoDraft',u,{draftId:d.draftId,abandon:true});assert.equal(c.cleanupClaimed,true);assert.equal(c.deletedCount,1);assert.equal(c.recoveryRequired,true);now=c.expiresAt;const r=await ok('cleanupReviewPhotoDraft',u,{draftId:d.draftId,abandon:false});assert.equal(r.observedAbsentCount,1);assert.equal(r.recoveryRequired,true);assert.equal(r.state,'cleanup');assert.equal((await db.doc('review_photo_drafts/'+d.draftId).get()).exists,true);});
 await check('pending publication status and cleanup preserve recovery until retry succeeds',async()=>{const u=await setup(),d=await create(u);await upload(u,d);denyPatch=true;await denied('publishReviewPhotoDraft',u,publishData(d),'UNAVAILABLE');const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.photoActivationState,'pending');assert.equal(s.recoveryRequired,true);const c=await ok('cleanupReviewPhotoDraft',u,{draftId:d.draftId,abandon:true});assert.equal(c.cleanupClaimed,false);assert.equal(c.recoveryRequired,true);denyPatch=false;now=s.expiresAt;assert.equal((await ok('publishReviewPhotoDraft',u,publishData(d))).photoActivationState,'complete');});
 await check('per-owner work budget charged before rejected decoding and status budget independent',async()=>{const u=await setup(),d=await create(u);for(let i=1;i<20;i++)await denied('uploadReviewPhotoAsset',u,{draftId:d.draftId,assetId:'one',imageBase64:String()},'INVALID_ARGUMENT');assert.equal((await quota(u).get()).data().count,20);await denied('uploadReviewPhotoAsset',u,{draftId:d.draftId,assetId:'one',imageBase64:normalized},'RESOURCE_EXHAUSTED');assert.equal((await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId})).state,'open');now+=60000;assert.equal((await upload(u,d)).state,'uploaded');assert.equal((await quota(u).get()).data().count,1);});
 await check('global work budget caps across independent authenticated owners',async()=>{const first=await setup();for(let i=0;i<60;i++){const u=i===0?first:await principal();await create(u);}const blocked=await principal();await denied('createReviewPhotoDraft',blocked,draftData(blocked),'RESOURCE_EXHAUSTED');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).data().count,60);assert.equal((await db.doc('review_photo_drafts/draft-'+blocked.actor).get()).exists,false);});
 await check('concurrent remaining global work slot admits exactly one',async()=>{const u=await setup();await db.doc('review_photo_rpc_limits/global_work').set({windowStart:Math.floor(now/60000)*60000,count:59});const results=await Promise.all([invoke('createReviewPhotoDraft',u,draftData(u,'race-a')),invoke('createReviewPhotoDraft',u,draftData(u,'race-b'))]);assert.equal(results.filter(r=>r.http===200).length,1);assert.equal(results.filter(r=>r.error==='RESOURCE_EXHAUSTED').length,1);assert.equal((await quota(u).get()).data().count,1);});
 await check('corrupt quota refuses before any allocation',async()=>{const u=await setup();await quota(u).set({windowStart:Math.floor(now/60000)*60000,count:0.5});await denied('createReviewPhotoDraft',u,draftData(u),'FAILED_PRECONDITION');assert.equal((await db.doc('review_photo_drafts/draft-'+u.actor).get()).exists,false);});
 await check('future quota refuses instead of resetting',async()=>{const u=await setup();await db.doc('review_photo_rpc_limits/global_work').set({windowStart:Math.floor(now/60000)*60000+60000,count:1});await denied('createReviewPhotoDraft',u,draftData(u),'FAILED_PRECONDITION');});
 await check('owner work budget does not spend another owners allocation',async()=>{const u=await setup();await quota(u).set({windowStart:Math.floor(now/60000)*60000,count:20});await denied('createReviewPhotoDraft',u,draftData(u),'RESOURCE_EXHAUSTED');const other=await principal();assert.equal((await create(other)).reviewId,other.actor);});
 await check('status owner budget remains bounded',async()=>{const u=await setup(),d=await create(u);await quota(u,'status').set({windowStart:Math.floor(now/60000)*60000,count:60});await denied('getReviewPhotoDraftStatus',u,{draftId:d.draftId},'RESOURCE_EXHAUSTED');assert.equal((await quota(u).get()).data().count,1);});
 await check('status global budget remains bounded',async()=>{const u=await setup(),d=await create(u);await db.doc('review_photo_rpc_limits/global_status').set({windowStart:Math.floor(now/60000)*60000,count:240});await denied('getReviewPhotoDraftStatus',u,{draftId:d.draftId},'RESOURCE_EXHAUSTED');});
 await check('safe status refuses corrupt bindings without exposing record',async()=>{const u=await setup(),d=await create(u);await db.doc('review_photo_drafts/'+d.draftId).update({uploads:{bad:{path:'foreign/photo.jpg',state:'uploaded'}}});await denied('getReviewPhotoDraftStatus',u,{draftId:d.draftId},'FAILED_PRECONDITION');});
 for(const [name,claims] of [['owner',{}],['foreign',{}],['admin',{admin:true}],['anonymous',null]])await check(name+' client cannot read/write private RPC budgets',async()=>{const context=claims===null?env.unauthenticatedContext():env.authenticatedContext(name,claims),r=doc(context.firestore(),'review_photo_rpc_limits/global_work');await assertFails(getDoc(r));await assertFails(setDoc(r,{windowStart:0,count:0}));});
 await check('completed historical status survives legitimate author deletion',async()=>{const u=await setup(),d=await create(u);await upload(u,d);await ok('publishReviewPhotoDraft',u,publishData(d));await deleteDoc(doc(env.authenticatedContext(u.actor).firestore(),'products/p/reviews/'+u.actor));const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.photoActivationState,'complete');assert.equal(s.stillCurrent,false);assert.equal(s.recoveryRequired,false);});
 await check('completed historical status survives later review replacement',async()=>{const u=await setup(),d=await create(u);await upload(u,d);await ok('publishReviewPhotoDraft',u,publishData(d));await db.doc('products/p/reviews/'+u.actor).update({photoDraftId:'later',photoActivationState:'pending',imageUrls:[]});const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.photoActivationState,'complete');assert.equal(s.stillCurrent,false);assert.equal(s.recoveryRequired,false);});
 await check('missing durable completion stamp requires recovery',async()=>{const u=await setup(),d=await create(u);await upload(u,d);await ok('publishReviewPhotoDraft',u,publishData(d));await db.doc('review_photo_drafts/'+d.draftId).update({photoActivatedAt:admin.firestore.FieldValue.delete()});const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.photoActivationState,'recovery_required');assert.equal(s.recoveryRequired,true);});
 await check('inconsistent durable content hash cannot report complete',async()=>{const u=await setup(),d=await create(u);await upload(u,d);await ok('publishReviewPhotoDraft',u,publishData(d));await db.doc('review_photo_drafts/'+d.draftId).update({contentHash:hash('different')});const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});assert.equal(s.photoActivationState,'recovery_required');assert.equal(s.recoveryRequired,true);});
 await check('oversized upload is rejected before budget or decoding',async()=>{const u=await setup();await denied('uploadReviewPhotoAsset',u,{draftId:'draft-'+u.actor,assetId:'one',imageBase64:'A'.repeat(Math.ceil(2*1024*1024/3)*4+4)},'INVALID_ARGUMENT');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('prototype upload asset is rejected before budget',async()=>{const u=await setup();await denied('uploadReviewPhotoAsset',u,{draftId:'draft-'+u.actor,assetId:'__proto__',imageBase64:normalized},'INVALID_ARGUMENT');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('nonnumeric publish and string cleanup intent reject before budget',async()=>{const u=await setup();await denied('publishReviewPhotoDraft',u,{draftId:'draft-'+u.actor,rating:'4',title:'Title',comment:'Comment'},'INVALID_ARGUMENT');await denied('cleanupReviewPhotoDraft',u,{draftId:'draft-'+u.actor,abandon:'true'},'INVALID_ARGUMENT');assert.equal((await db.doc('review_photo_rpc_limits/global_work').get()).exists,false);});
 await check('rollout rollback blocks new work but allows status and owner cleanup',async()=>{const u=await setup(),d=await create(u);await upload(u,d);enabled=false;await denied('createReviewPhotoDraft',u,draftData(u,'another'),'FAILED_PRECONDITION');await denied('uploadReviewPhotoAsset',u,{draftId:d.draftId,assetId:'one',imageBase64:normalized},'FAILED_PRECONDITION');assert.equal((await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId})).state,'open');await denied('publishReviewPhotoDraft',u,publishData(d),'FAILED_PRECONDITION');assert.equal((await db.doc('products/p/reviews/'+u.actor).get()).exists,false);const c=await ok('cleanupReviewPhotoDraft',u,{draftId:d.draftId,abandon:true});assert.equal(c.cleanupClaimed,true);assert.equal(c.recoveryRequired,true);});
 await check('already-linked recovery survives rollout rollback and expiry',async()=>{const u=await setup(),d=await create(u);await upload(u,d);denyPatch=true;await denied('publishReviewPhotoDraft',u,publishData(d),'UNAVAILABLE');const s=await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId});enabled=false;denyPatch=false;now=s.expiresAt;assert.equal((await ok('publishReviewPhotoDraft',u,publishData(d))).photoActivationState,'complete');assert.equal((await ok('getReviewPhotoDraftStatus',u,{draftId:d.draftId})).recoveryRequired,false);});
 await check('ready unlinked plan cannot publish a new review during rollback',async()=>{const u=await setup(),d=await create(u);await upload(u,d);const core=require('../lib/seller/reviewPhotoDraftCore'),c={rating:4,title:'Title',comment:'Comment',userName:'Original profile',userAvatar:''};await core.freezePhotoContent(db,u.actor,d.draftId,c,()=>now);const inspected=await core.inspectPhotoPublication(db,u.actor,d.draftId,()=>now);await core.preparePhotoAccessPlan(db,u.actor,d.draftId,B,inspected.uploads,()=>now);enabled=false;await denied('publishReviewPhotoDraft',u,publishData(d),'FAILED_PRECONDITION');assert.equal((await db.doc('products/p/reviews/'+u.actor).get()).exists,false);const [m]=await bucket.file('review_drafts/'+u.actor+'/'+d.draftId+'/one.jpg').getMetadata();assert.equal(Object.hasOwn(m.metadata||{},'firebaseStorageDownloadTokens'),false);});
 await check('completed receipt retry survives rollback without new capability writes',async()=>{const u=await setup(),d=await create(u);await upload(u,d);await ok('publishReviewPhotoDraft',u,publishData(d));enabled=false;denyPatch=true;assert.equal((await ok('publishReviewPhotoDraft',u,publishData(d))).photoActivationState,'complete');});
 console.log(`SUMMARY ${passed} passed ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error('Unexpected RPC fixture failure: '+e.name+' '+e.message);process.exitCode=1;}).finally(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(env)await env.cleanup();await app.delete();});
