// Real transaction cores, synthetic demo Firestore; malformed records must have no effects.
const assert=require('node:assert/strict');
if(!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Loopback emulator required');
process.env.GCLOUD_PROJECT='demo-foundation-rider-balances';
const admin=require('firebase-admin');admin.initializeApp({projectId:process.env.GCLOUD_PROJECT});const db=admin.firestore();
const {Timestamp}=require('firebase-admin/firestore');const M=require('../lib/delivery/riderMoney');
const {DEFAULT_RIDER_PAY_RATES:R}=require('../lib/delivery/riderPay');
const NOW=Date.UTC(2026,9,5,1);let seq=0,passed=0,failed=0;
async function scenario(label,fn){try{await fn();passed++;console.log(`PASS ${label}`);}catch(e){failed++;console.log(`FAIL ${label}: ${e.message}`);}}
const bad=e=>e.code==='failed-precondition'&&e.details?.reason==='bad_money_state';
const get=async p=>(await db.doc(p).get()).data();
async function fixture(fields={cashHeld:100,earningsUnsettled:10},total=20){const id=`fixture_balance_${++seq}`;await db.doc(`rider_accounts/${id}`).set(fields);await db.doc(`delivery_partners/${id}`).set({status:'approved',upiId:'fixture@example.invalid'});await db.doc(`orders/${id}`).set({deliveryPartnerId:id,orderStatus:'delivered',status:'delivered',paymentMethod:'cod',total});return id;}
async function noEarningEffects(id){assert.equal((await db.doc(`rider_earnings/${id}`).get()).exists,false);assert.equal((await db.collection('rider_cash_ledger').where('riderId','==',id).get()).size,0);assert.equal((await get(`orders/${id}`)).codSettlementStatus,undefined);}
async function line(id,fields={total:10,totalPaise:1000},suffix='a'){await db.doc(`rider_earnings/${id}_${suffix}`).set({riderId:id,statementId:null,createdAt:Timestamp.fromMillis(NOW-86400000*3),...fields});}
async function noStatementEffects(id){assert.equal((await db.collection('rider_payouts').where('riderId','==',id).get()).size,0);assert.equal((await get(`rider_earnings/${id}_a`)).statementId,null);assert.equal((await db.collection('rider_cash_ledger').where('riderId','==',id).get()).size,0);}
(async()=>{
 const invalid=[['cashHeld',-1e-12],['cashHeld','100'],['cashHeld',NaN],['cashHeld',1.001],['cashHeld',-1],['cashHeldPaise',null],['cashHeldPaise',1.5],['cashHeldPaise',Number.MAX_SAFE_INTEGER+1],['earningsUnsettled','10'],['earningsUnsettled',Infinity],['earningsUnsettledPaise',.5]];
 for(const [key,value] of invalid){
  await scenario(`earning rejects ${key}=${String(value)}`,async()=>{const fields={cashHeld:100,earningsUnsettled:10,[key]:value},id=await fixture(fields);await assert.rejects(M.recordDeliveryEarningCore(db,id,NOW,R),bad);await noEarningEffects(id);assert.deepEqual(await get(`rider_accounts/${id}`),fields);});
  await scenario(`statement rejects ${key}=${String(value)}`,async()=>{const fields={cashHeld:100,earningsUnsettled:10,[key]:value},id=await fixture(fields);await line(id);await assert.rejects(M.buildStatementCore(db,id,NOW),bad);await noStatementEffects(id);assert.deepEqual(await get(`rider_accounts/${id}`),fields);});
 }
 for(const total of ['20',NaN,Infinity,1.001,-1,-1e-12,Number.MAX_SAFE_INTEGER])await scenario(`COD rejects total ${String(total)}`,async()=>{const id=await fixture(undefined,total);await assert.rejects(M.recordDeliveryEarningCore(db,id,NOW,R),bad);await noEarningEffects(id);});
 for(const fields of [{total:-1e-12},{total:'10'},{total:1.001},{totalPaise:null,total:10},{totalPaise:.5,total:10},{totalPaise:-1,total:10},{totalPaise:Number.MAX_SAFE_INTEGER+1,total:10},{}])await scenario(`statement rejects corrupt earning ${JSON.stringify(fields)}`,async()=>{const id=await fixture();await line(id,fields);await assert.rejects(M.buildStatementCore(db,id,NOW),bad);await noStatementEffects(id);});
 await scenario('earning account addition cannot overflow',async()=>{const id=await fixture({cashHeldPaise:Number.MAX_SAFE_INTEGER-1,earningsUnsettledPaise:0},20);await assert.rejects(M.recordDeliveryEarningCore(db,id,NOW,R),bad);await noEarningEffects(id);});
 await scenario('statement selected line sum cannot overflow',async()=>{const id=await fixture({cashHeldPaise:0,earningsUnsettledPaise:100});await line(id,{totalPaise:Number.MAX_SAFE_INTEGER-1});await line(id,{totalPaise:10},'b');await assert.rejects(M.buildStatementCore(db,id,NOW),bad);await noStatementEffects(id);});
 await scenario('statement debt subtraction cannot overflow',async()=>{const id=await fixture({cashHeldPaise:0,earningsUnsettledPaise:-Number.MAX_SAFE_INTEGER+1});await line(id);await assert.rejects(M.buildStatementCore(db,id,NOW),bad);await noStatementEffects(id);});
 await scenario('paise authority ignores stale rupee display',async()=>{const id=await fixture({cashHeld:'stale',cashHeldPaise:3,earningsUnsettled:999,earningsUnsettledPaise:-2},.01);const r=await M.recordDeliveryEarningCore(db,id,NOW,R);assert.equal(r.kind,'created');const a=await get(`rider_accounts/${id}`);assert.equal(a.cashHeldPaise,4);assert.equal(a.earningsUnsettledPaise,Math.round(r.total*100)-2);});
 await scenario('legacy float noise and signed debt remain valid',async()=>{const id=await fixture({cashHeld:.1+.2,earningsUnsettled:-1.23},.01);const r=await M.recordDeliveryEarningCore(db,id,NOW,R);const a=await get(`rider_accounts/${id}`);assert.equal(a.cashHeldPaise,31);assert.equal(a.earningsUnsettledPaise,Math.round(r.total*100)-123);});
 await scenario('valid legacy earning settled with exact cents',async()=>{const id=await fixture({cashHeldPaise:0,earningsUnsettledPaise:29});await line(id,{total:.1+.2});const v=await M.buildStatementCore(db,id,NOW);assert.equal(v.kind,'created');assert.equal(v.amount,.3);assert.equal((await get(`rider_accounts/${id}`)).earningsUnsettledPaise,-1);});
 await scenario('two earning retries collect and pay once',async()=>{const id=await fixture();const v=await Promise.all([M.recordDeliveryEarningCore(db,id,NOW,R),M.recordDeliveryEarningCore(db,id,NOW,R)]);assert.equal(v.filter(x=>x.kind==='created').length,1);assert.equal((await get(`rider_accounts/${id}`)).cashHeldPaise,12000);assert.equal((await db.collection('rider_cash_ledger').where('riderId','==',id).get()).size,1);});
 await scenario('missing COD total cannot become zero cash',async()=>{const id=await fixture();await db.doc(`orders/${id}`).update({total:admin.firestore.FieldValue.delete()});await assert.rejects(M.recordDeliveryEarningCore(db,id,NOW,R),bad);await noEarningEffects(id);});
 await scenario('completed earning retry remains effect free with later corruption',async()=>{const id=await fixture();await M.recordDeliveryEarningCore(db,id,NOW,R);await db.doc(`rider_accounts/${id}`).update({cashHeldPaise:null});const before=await get(`rider_accounts/${id}`);assert.equal((await M.recordDeliveryEarningCore(db,id,NOW,R)).kind,'already');assert.deepEqual(await get(`rider_accounts/${id}`),before);assert.equal((await db.collection('rider_cash_ledger').where('riderId','==',id).get()).size,1);});
 await scenario('future malformed line is not consumed by this statement',async()=>{const id=await fixture({cashHeldPaise:0,earningsUnsettledPaise:1000});await line(id);await line(id,{total:null,createdAt:Timestamp.fromMillis(NOW+86400000)},'future');const v=await M.buildStatementCore(db,id,NOW);assert.equal(v.kind,'created');assert.equal(v.amount,10);assert.equal((await get(`rider_earnings/${id}_future`)).statementId,null);});
 await scenario('completed statement retry remains effect free with later corruption',async()=>{const id=await fixture({cashHeldPaise:0,earningsUnsettledPaise:1000});await line(id);await M.buildStatementCore(db,id,NOW);await db.doc(`rider_accounts/${id}`).update({earningsUnsettledPaise:null});const before=await get(`rider_accounts/${id}`);assert.equal((await M.buildStatementCore(db,id,NOW)).kind,'exists');assert.deepEqual(await get(`rider_accounts/${id}`),before);assert.equal((await db.collection('rider_payouts').where('riderId','==',id).get()).size,1);});
 console.log(`RESULT ${passed} passed; ${failed} failed`);await db.terminate();if(failed)process.exitCode=1;
})().catch(async e=>{console.error(e.stack);await db.terminate();process.exitCode=1;});
