class IndiaLocations {
  static final Map<String, Map<String, List<String>>> stateDistrictCity = {
    'Andhra Pradesh': {
      'Anantapur': ['Anantapur', 'Hindupur', 'Kadiri', 'Tadipatri', 'Guntakal'],
      'Chittoor': ['Tirupati', 'Chittoor', 'Madanapalle', 'Srikalahasti', 'Palamaner'],
      'East Godavari': ['Kakinada', 'Rajahmundry', 'Amalapuram', 'Peddapuram', 'Ramachandrapuram'],
      'Guntur': ['Guntur', 'Tenali', 'Narasaraopet', 'Chilakaluripet', 'Mangalagiri'],
      'Krishna': ['Vijayawada', 'Machilipatnam', 'Gudivada', 'Nuzvid', 'Jaggayyapeta'],
      'Kurnool': ['Kurnool', 'Nandyal', 'Adoni', 'Dhone', 'Yemmiganur'],
      'Prakasam': ['Ongole', 'Chirala', 'Kandukur', 'Markapur', 'Addanki'],
      'Srikakulam': ['Srikakulam', 'Amadalavalasa', 'Ichchapuram', 'Palasa', 'Tekkali'],
      'Visakhapatnam': ['Visakhapatnam', 'Anakapalli', 'Narsipatnam', 'Bheemunipatnam', 'Yelamanchili'],
      'Vizianagaram': ['Vizianagaram', 'Bobbili', 'Parvathipuram', 'Salur', 'Gajapathinagaram'],
      'West Godavari': ['Eluru', 'Bhimavaram', 'Tadepalligudem', 'Tanuku', 'Narsapuram'],
      'YSR Kadapa': ['Kadapa', 'Proddatur', 'Jammalamadugu', 'Rajampet', 'Badvel'],
    },
    'Telangana': {
      'Hyderabad': ['Hyderabad', 'Secunderabad', 'Kukatpally', 'LB Nagar', 'Uppal'],
      'Karimnagar': ['Karimnagar', 'Jagtial', 'Sircilla', 'Peddapalli', 'Huzurabad'],
      'Khammam': ['Khammam', 'Kothagudem', 'Yellandu', 'Bhadrachalam', 'Madhira'],
      'Mahbubnagar': ['Mahbubnagar', 'Wanaparthy', 'Gadwal', 'Nagarkurnool', 'Kalwakurthy'],
      'Medak': ['Sangareddy', 'Medak', 'Siddipet', 'Narayankhed', 'Ramayampet'],
      'Nalgonda': ['Nalgonda', 'Suryapet', 'Miryalaguda', 'Bhongir', 'Devarakonda'],
      'Nizamabad': ['Nizamabad', 'Bodhan', 'Armoor', 'Kamareddy', 'Banswada'],
      'Rangareddy': ['Shamshabad', 'Tandur', 'Vikarabad', 'Kodangal', 'Maheshwaram'],
      'Warangal': ['Warangal', 'Hanamkonda', 'Jangaon', 'Bhupalpally', 'Mulugu'],
    },
    'Karnataka': {
      'Bangalore Urban': ['Bengaluru', 'Yelahanka', 'Byatarayanapura', 'Anekal', 'Devanahalli'],
      'Bangalore Rural': ['Doddaballapura', 'Nelamangala', 'Hosakote', 'Hoskote'],
      'Belgaum': ['Belgaum', 'Chikodi', 'Bailhongal', 'Athani', 'Raybag'],
      'Bellary': ['Bellary', 'Hospet', 'Sandur', 'Kudligi', 'Hadagali'],
      'Bidar': ['Bidar', 'Bhalki', 'Basavakalyan', 'Aurad', 'Humnabad'],
      'Mysore': ['Mysuru', 'Nanjangud', 'KR Nagar', 'Hunsur', 'Piriyapatna'],
      'Mangalore': ['Mangalore', 'Bantwal', 'Puttur', 'Sullia', 'Belthangady'],
      'Hubli-Dharwad': ['Hubli', 'Dharwad', 'Kalghatgi', 'Kundagol', 'Navalgund'],
    },
    'Tamil Nadu': {
      'Chennai': ['Chennai', 'Tambaram', 'Avadi', 'Pallavaram', 'Ambattur'],
      'Coimbatore': ['Coimbatore', 'Pollachi', 'Valparai', 'Mettupalayam', 'Tiruppur'],
      'Madurai': ['Madurai', 'Dindigul', 'Melur', 'Vadipatti', 'Usilampatti'],
      'Salem': ['Salem', 'Attur', 'Mettur', 'Omalur', 'Sankagiri'],
      'Tiruchirappalli': ['Tiruchirappalli', 'Lalgudi', 'Manapparai', 'Srirangam', 'Ariyalur'],
      'Tirunelveli': ['Tirunelveli', 'Nellai', 'Palayamkottai', 'Ambasamudram', 'Sankarankoil'],
      'Vellore': ['Vellore', 'Arcot', 'Ranipet', 'Katpadi', 'Gudiyatham'],
      'Erode': ['Erode', 'Bhavani', 'Gobichettipalayam', 'Sathyamangalam', 'Perundurai'],
    },
    'Maharashtra': {
      'Mumbai City': ['Mumbai', 'Colaba', 'Churchgate', 'Marine Lines', 'Charni Road'],
      'Mumbai Suburban': ['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Kurla'],
      'Pune': ['Pune', 'Pimpri-Chinchwad', 'Baramati', 'Talegaon', 'Lonavala'],
      'Nagpur': ['Nagpur', 'Kamptee', 'Hingna', 'Umred', 'Kuhi'],
      'Thane': ['Thane', 'Kalyan', 'Dombivli', 'Bhiwandi', 'Ulhasnagar'],
      'Nashik': ['Nashik', 'Malegaon', 'Sinnar', 'Igatpuri', 'Dindori'],
      'Aurangabad': ['Aurangabad', 'Jalna', 'Paithan', 'Gangapur', 'Sillod'],
      'Solapur': ['Solapur', 'Pandharpur', 'Akkalkot', 'Barshi', 'Mohol'],
    },
    'Kerala': {
      'Thiruvananthapuram': ['Thiruvananthapuram', 'Neyyattinkara', 'Attingal', 'Varkala', 'Nedumangad'],
      'Kochi': ['Kochi', 'Ernakulam', 'Aluva', 'Perumbavoor', 'Kalamassery'],
      'Kozhikode': ['Kozhikode', 'Vatakara', 'Koyilandy', 'Feroke', 'Balussery'],
      'Thrissur': ['Thrissur', 'Chalakudy', 'Irinjalakuda', 'Kodungallur', 'Guruvayur'],
      'Kollam': ['Kollam', 'Karunagappally', 'Chavara', 'Paravur', 'Punalur'],
      'Kannur': ['Kannur', 'Thalassery', 'Payyanur', 'Mattannur', 'Taliparamba'],
      'Kottayam': ['Kottayam', 'Changanassery', 'Pala', 'Ettumanoor', 'Vaikom'],
      'Palakkad': ['Palakkad', 'Ottappalam', 'Shornur', 'Mannarkkad', 'Chittur'],
    },
    'Gujarat': {
      'Ahmedabad': ['Ahmedabad', 'Gandhinagar', 'Sanand', 'Dholka', 'Bavla'],
      'Surat': ['Surat', 'Navsari', 'Valsad', 'Bardoli', 'Vyara'],
      'Vadodara': ['Vadodara', 'Ankleshwar', 'Bharuch', 'Dabhoi', 'Padra'],
      'Rajkot': ['Rajkot', 'Jamnagar', 'Morbi', 'Gondal', 'Jetpur'],
      'Bhavnagar': ['Bhavnagar', 'Mahuva', 'Sihor', 'Palitana', 'Talaja'],
      'Junagadh': ['Junagadh', 'Veraval', 'Mangrol', 'Keshod', 'Bhesan'],
      'Mehsana': ['Mehsana', 'Patan', 'Visnagar', 'Unjha', 'Kadi'],
      'Gandhinagar': ['Gandhinagar', 'Kalol', 'Mansa', 'Dehgam'],
    },
    'Rajasthan': {
      'Jaipur': ['Jaipur', 'Ajmer', 'Kishangarh', 'Chaksu', 'Kotputli'],
      'Jodhpur': ['Jodhpur', 'Pali', 'Bilara', 'Osian', 'Bhopalgarh'],
      'Kota': ['Kota', 'Bundi', 'Jhalawar', 'Baran', 'Mangrol'],
      'Bikaner': ['Bikaner', 'Nokha', 'Sri Ganganagar', 'Hanumangarh', 'Suratgarh'],
      'Udaipur': ['Udaipur', 'Chittorgarh', 'Bhilwara', 'Rajsamand', 'Nathdwara'],
      'Alwar': ['Alwar', 'Bhiwadi', 'Tijara', 'Rajgarh', 'Ramgarh'],
      'Bharatpur': ['Bharatpur', 'Dholpur', 'Deeg', 'Kumher', 'Weir'],
      'Sikar': ['Sikar', 'Jhunjhunu', 'Fatehpur', 'Sri Madhopur', 'Danta Ramgarh'],
    },
    'West Bengal': {
      'Kolkata': ['Kolkata', 'Howrah', 'Salt Lake', 'Tollygunge', 'Behala'],
      'North 24 Parganas': ['Barasat', 'Barrackpore', 'Habra', 'Basirhat', 'Bongaon'],
      'South 24 Parganas': ['Alipore', 'Baruipur', 'Canning', 'Diamond Harbour', 'Kakdwip'],
      'Darjeeling': ['Darjeeling', 'Siliguri', 'Kurseong', 'Kalimpong', 'Mirik'],
      'Jalpaiguri': ['Jalpaiguri', 'Alipurduar', 'Mal', 'Dhupguri', 'Maynaguri'],
      'Bardhaman': ['Asansol', 'Durgapur', 'Bardhaman', 'Kalna', 'Katwa'],
      'Murshidabad': ['Berhampore', 'Murshidabad', 'Kandi', 'Jangipur', 'Domkal'],
      'Nadia': ['Krishnanagar', 'Ranaghat', 'Kalyani', 'Nabadwip', 'Chakdaha'],
    },
    'Madhya Pradesh': {
      'Bhopal': ['Bhopal', 'Berasia', 'Huzur', 'Sehore', 'Raisen'],
      'Indore': ['Indore', 'Mhow', 'Sanwer', 'Depalpur', 'Hatod'],
      'Jabalpur': ['Jabalpur', 'Katni', 'Sihora', 'Panagar', 'Patan'],
      'Gwalior': ['Gwalior', 'Morena', 'Bhind', 'Shivpuri', 'Dabra'],
      'Ujjain': ['Ujjain', 'Dewas', 'Shajapur', 'Nagda', 'Mahidpur'],
      'Sagar': ['Sagar', 'Damoh', 'Khurai', 'Bina', 'Rehli'],
      'Ratlam': ['Ratlam', 'Mandsaur', 'Neemuch', 'Jaora', 'Sailana'],
      'Satna': ['Satna', 'Maihar', 'Nagod', 'Amarpatan', 'Ramnagar'],
    },
    'Uttar Pradesh': {
      'Lucknow': ['Lucknow', 'Malihabad', 'Mohanlalganj', 'Bakshi Ka Talab'],
      'Kanpur': ['Kanpur', 'Kanpur Dehat', 'Akbarpur', 'Ghatampur', 'Bilhaur'],
      'Ghaziabad': ['Ghaziabad', 'Hapur', 'Modi Nagar', 'Muradnagar', 'Loni'],
      'Agra': ['Agra', 'Mathura', 'Fatehabad', 'Kiraoli', 'Bah'],
      'Meerut': ['Meerut', 'Baghpat', 'Sardhana', 'Khatauli', 'Mawana'],
      'Varanasi': ['Varanasi', 'Chandauli', 'Mughalsarai', 'Bhadohi', 'Jaunpur'],
      'Allahabad': ['Prayagraj', 'Phulpur', 'Soraon', 'Handia', 'Meja'],
      'Bareilly': ['Bareilly', 'Aonla', 'Baheri', 'Faridpur', 'Meerganj'],
      'Gorakhpur': ['Gorakhpur', 'Deoria', 'Kushinagar', 'Maharajganj', 'Bansgaon'],
      'Noida': ['Noida', 'Greater Noida', 'Dadri', 'Jewar', 'Dankaur'],
    },
    'Delhi': {
      'Central Delhi': ['Connaught Place', 'Karol Bagh', 'Paharganj', 'Daryaganj', 'Chandni Chowk'],
      'North Delhi': ['Civil Lines', 'Model Town', 'Rohini', 'Pitampura', 'Shalimar Bagh'],
      'South Delhi': ['Hauz Khas', 'Saket', 'Kalkaji', 'Defence Colony', 'Greater Kailash'],
      'East Delhi': ['Laxmi Nagar', 'Shahdara', 'Preet Vihar', 'Mayur Vihar', 'Patparganj'],
      'West Delhi': ['Janakpuri', 'Rajouri Garden', 'Tilak Nagar', 'Vikaspuri', 'Paschim Vihar'],
      'New Delhi': ['Chanakyapuri', 'Diplomatic Enclave', 'RK Puram', 'Vasant Vihar', 'Lodhi Colony'],
      'North East Delhi': ['Seelampur', 'Shahdara', 'Karawal Nagar', 'Nand Nagri', 'Gokulpuri'],
      'North West Delhi': ['Kanjhawala', 'Bawana', 'Narela', 'Alipur', 'Burari'],
      'South East Delhi': ['Kalkaji', 'Okhla', 'Govindpuri', 'Jaitpur', 'Badarpur'],
      'South West Delhi': ['Dwarka', 'Najafgarh', 'Kapashera', 'Palam', 'Vasant Kunj'],
      'Shahdara': ['Shahdara', 'Dilshad Garden', 'Khajuri Khas', 'Seelam Pur', 'Shastri Park'],
    },
    'Punjab': {
      'Ludhiana': ['Ludhiana', 'Jagraon', 'Khanna', 'Raikot', 'Samrala'],
      'Amritsar': ['Amritsar', 'Tarn Taran', 'Majitha', 'Ajnala', 'Rayya'],
      'Jalandhar': ['Jalandhar', 'Kapurthala', 'Nakodar', 'Phillaur', 'Shahkot'],
      'Patiala': ['Patiala', 'Sangrur', 'Rajpura', 'Samana', 'Nabha'],
      'Bathinda': ['Bathinda', 'Mansa', 'Talwandi Sabo', 'Rampura Phul'],
      'Mohali': ['Mohali', 'Kharar', 'Derabassi', 'Zirakpur', 'Lalru'],
      'Hoshiarpur': ['Hoshiarpur', 'Garhshankar', 'Dasuya', 'Mukerian', 'Talwara'],
      'Firozpur': ['Firozpur', 'Fazilka', 'Abohar', 'Zira', 'Jalalabad'],
    },
    'Haryana': {
      'Gurugram': ['Gurugram', 'Manesar', 'Pataudi', 'Sohna', 'Farukh Nagar'],
      'Faridabad': ['Faridabad', 'Ballabgarh', 'Palwal', 'Hodal', 'Hathin'],
      'Hisar': ['Hisar', 'Hansi', 'Barwala', 'Narnaund', 'Uklana'],
      'Panipat': ['Panipat', 'Samalkha', 'Israna', 'Madlauda', 'Bapoli'],
      'Ambala': ['Ambala', 'Jagadhri', 'Naraingarh', 'Barara', 'Saha'],
      'Rohtak': ['Rohtak', 'Meham', 'Kalanaur', 'Sampla', 'Maham'],
      'Karnal': ['Karnal', 'Assandh', 'Gharaunda', 'Nilokheri', 'Indri'],
      'Sonipat': ['Sonipat', 'Ganaur', 'Gohana', 'Kharkhoda', 'Rai'],
    },
    'Bihar': {
      'Patna': ['Patna', 'Danapur', 'Phulwari Sharif', 'Maner', 'Barh'],
      'Gaya': ['Gaya', 'Bodh Gaya', 'Tekari', 'Sherghati', 'Manpur'],
      'Bhagalpur': ['Bhagalpur', 'Kahalgaon', 'Naugachhia', 'Sultanganj', 'Sabour'],
      'Muzaffarpur': ['Muzaffarpur', 'Motihari', 'Sitamarhi', 'Sheohar', 'Kanti'],
      'Darbhanga': ['Darbhanga', 'Madhubani', 'Samastipur', 'Jale', 'Keoti'],
      'Purnia': ['Purnia', 'Araria', 'Kishanganj', 'Katihar', 'Dhamdaha'],
      'Bhojpur': ['Ara', 'Jagdishpur', 'Piro', 'Sandesh', 'Shahpur'],
      'Nalanda': ['Bihar Sharif', 'Rajgir', 'Hilsa', 'Asthawan', 'Harnaut'],
    },
    'Odisha': {
      'Bhubaneswar': ['Bhubaneswar', 'Khordha', 'Jatani', 'Balianta', 'Balipatna'],
      'Cuttack': ['Cuttack', 'Jagatsinghpur', 'Kendrapara', 'Banki', 'Athagad'],
      'Berhampur': ['Berhampur', 'Ganjam', 'Chhatrapur', 'Gopalpur', 'Digapahandi'],
      'Sambalpur': ['Sambalpur', 'Jharsuguda', 'Bargarh', 'Burla', 'Hirakud'],
      'Rourkela': ['Rourkela', 'Sundargarh', 'Rajgangpur', 'Bisra', 'Biramitrapur'],
      'Balasore': ['Balasore', 'Bhadrak', 'Jaleswar', 'Basta', 'Remuna'],
      'Puri': ['Puri', 'Konark', 'Nimapara', 'Satyabadi', 'Pipili'],
      'Angul': ['Angul', 'Talcher', 'Athamallik', 'Banarpal', 'Kaniha'],
    },
    'Jharkhand': {
      'Ranchi': ['Ranchi', 'Bundu', 'Kanke', 'Namkum', 'Ormanjhi'],
      'Jamshedpur': ['Jamshedpur', 'Jugsalai', 'Mango', 'Dhalbhumgarh', 'Potka'],
      'Dhanbad': ['Dhanbad', 'Jharia', 'Sindri', 'Katras', 'Tundi'],
      'Bokaro': ['Bokaro Steel City', 'Chas', 'Phusro', 'Bermo', 'Gomia'],
      'Hazaribagh': ['Hazaribagh', 'Ramgarh', 'Chatra', 'Barhi', 'Mandu'],
      'Giridih': ['Giridih', 'Bengabad', 'Tisri', 'Dumri', 'Jamua'],
      'Deoghar': ['Deoghar', 'Madhupur', 'Jasidih', 'Sarath', 'Mohanpur'],
      'Dumka': ['Dumka', 'Shikaripara', 'Kathikund', 'Jama', 'Jarmundi'],
    },
    'Assam': {
      'Guwahati': ['Guwahati', 'Dispur', 'Beltola', 'Jalukbari', 'Khanapara'],
      'Dibrugarh': ['Dibrugarh', 'Tinsukia', 'Naharkatiya', 'Margherita', 'Chabua'],
      'Jorhat': ['Jorhat', 'Titabar', 'Mariani', 'Teok', 'Majuli'],
      'Silchar': ['Silchar', 'Karimganj', 'Hailakandi', 'Lakhipur', 'Badarpur'],
      'Nagaon': ['Nagaon', 'Hojai', 'Morigaon', 'Raha', 'Dhing'],
      'Tezpur': ['Tezpur', 'Mangaldoi', 'Udalguri', 'Dhekiajuli', 'Missamari'],
      'Bongaigaon': ['Bongaigaon', 'Kokrajhar', 'Bijni', 'Abhayapuri', 'Chirang'],
      'Goalpara': ['Goalpara', 'Dhubri', 'South Salmara', 'Bilasipara', 'Mankachar'],
    },
    'Chhattisgarh': {
      'Raipur': ['Raipur', 'Durg', 'Bhilai', 'Abhanpur', 'Tilda'],
      'Bilaspur': ['Bilaspur', 'Korba', 'Raigarh', 'Champa', 'Katghora'],
      'Durg': ['Durg', 'Bhilai', 'Rajnandgaon', 'Balod', 'Patan'],
      'Jagdalpur': ['Jagdalpur', 'Bastar', 'Kondagaon', 'Kanker', 'Narayanpur'],
      'Korba': ['Korba', 'Katghora', 'Pali', 'Kartala', 'Dipka'],
      'Raigarh': ['Raigarh', 'Gharghoda', 'Kharsia', 'Dharamjaigarh', 'Sarangarh'],
      'Ambikapur': ['Ambikapur', 'Surguja', 'Surajpur', 'Baikunthpur', 'Premnagar'],
      'Mahasamund': ['Mahasamund', 'Saraipali', 'Basna', 'Pithora', 'Bagbahra'],
    },
    'Uttarakhand': {
      'Dehradun': ['Dehradun', 'Mussoorie', 'Rishikesh', 'Vikasnagar', 'Chakrata'],
      'Haridwar': ['Haridwar', 'Roorkee', 'Jwalapur', 'Laksar', 'Manglaur'],
      'Nainital': ['Nainital', 'Haldwani', 'Ramnagar', 'Bhimtal', 'Kaladhungi'],
      'Almora': ['Almora', 'Ranikhet', 'Bageshwar', 'Dwarahat', 'Someshwar'],
      'Rudrapur': ['Rudrapur', 'Kichha', 'Sitarganj', 'Kashipur', 'Jaspur'],
      'Pithoragarh': ['Pithoragarh', 'Dharchula', 'Munsiyari', 'Didihat', 'Gangolihat'],
      'Pauri': ['Pauri', 'Srinagar', 'Kotdwar', 'Lansdowne', 'Dhumakot'],
      'Tehri': ['Tehri', 'Narendra Nagar', 'Dhanaulti', 'Chamba', 'Devprayag'],
    },
    'Himachal Pradesh': {
      'Shimla': ['Shimla', 'Solan', 'Kasauli', 'Parwanoo', 'Kandaghat'],
      'Mandi': ['Mandi', 'Sundernagar', 'Jogindernagar', 'Karsog', 'Thunag'],
      'Kullu': ['Kullu', 'Manali', 'Bhuntar', 'Manikaran', 'Naggar'],
      'Kangra': ['Dharamshala', 'Kangra', 'Palampur', 'Baijnath', 'Jawali'],
      'Hamirpur': ['Hamirpur', 'Sujanpur', 'Barsar', 'Nadaun', 'Bhoranj'],
      'Una': ['Una', 'Amb', 'Gagret', 'Haroli', 'Bangana'],
      'Bilaspur': ['Bilaspur', 'Ghumarwin', 'Naina Devi', 'Jhandutta', 'Sadar'],
      'Chamba': ['Chamba', 'Dalhousie', 'Bharmour', 'Tissa', 'Salooni'],
    },
    'Jammu and Kashmir': {
      'Srinagar': ['Srinagar', 'Ganderbal', 'Budgam', 'Pulwama', 'Anantnag'],
      'Jammu': ['Jammu', 'Kathua', 'Samba', 'Udhampur', 'Reasi'],
      'Anantnag': ['Anantnag', 'Bijbehara', 'Pahalgam', 'Kokernag', 'Dooru'],
      'Baramulla': ['Baramulla', 'Uri', 'Sopore', 'Pattan', 'Singhpora'],
      'Kupwara': ['Kupwara', 'Handwara', 'Lolab', 'Karnah', 'Machil'],
      'Rajouri': ['Rajouri', 'Thanamandi', 'Kalakote', 'Nowshera', 'Darhal'],
      'Poonch': ['Poonch', 'Surankote', 'Mendhar', 'Haveli', 'Mandi'],
      'Doda': ['Doda', 'Bhaderwah', 'Kishtwar', 'Ramban', 'Banihal'],
    },
    'Goa': {
      'North Goa': ['Panaji', 'Mapusa', 'Pernem', 'Bicholim', 'Ponda'],
      'South Goa': ['Margao', 'Quepem', 'Curchorem', 'Canacona', 'Sanvordem'],
    },
    'Manipur': {
      'Imphal West': ['Imphal', 'Lamphelpat', 'Lamshang', 'Patsoi', 'Wangoi'],
      'Imphal East': ['Porompat', 'Jiribam', 'Andro', 'Sawombung', 'Irilbung'],
      'Thoubal': ['Thoubal', 'Lilong', 'Yairipok', 'Kakching', 'Wangjing'],
      'Bishnupur': ['Bishnupur', 'Moirang', 'Nambol', 'Ngaikhong', 'Kumbi'],
      'Churachandpur': ['Churachandpur', 'Thanlon', 'Singngat', 'Hengolep', 'Samulamlan'],
    },
    'Meghalaya': {
      'East Khasi Hills': ['Shillong', 'Sohra', 'Mawlai', 'Pynursla', 'Mawphlang'],
      'West Garo Hills': ['Tura', 'Ampati', 'Dadenggiri', 'Tikrikilla', 'Resubelpara'],
      'Jaintia Hills': ['Jowai', 'Amlarem', 'Rymbai', 'Thadlaskein', 'Saipung'],
      'Ri Bhoi': ['Nongpoh', 'Umsning', 'Patharkhmah', 'Jirang', 'Byrnihat'],
    },
    'Tripura': {
      'West Tripura': ['Agartala', 'Mohanpur', 'Jirania', 'Ranirbazar', 'Bishalgarh'],
      'South Tripura': ['Udaipur', 'Amarpur', 'Belonia', 'Sabroom', 'Rupaichhari'],
      'Dhalai': ['Ambassa', 'Kamalpur', 'Chawmanu', 'Salema', 'Manu'],
      'North Tripura': ['Dharmanagar', 'Kanchanpur', 'Pencharthal', 'Kadamtala'],
    },
    'Mizoram': {
      'Aizawl': ['Aizawl', 'Darlawn', 'Thingsulthliah', 'Champhai', 'Bawngkawn'],
      'Lunglei': ['Lunglei', 'Bunghmun', 'Ngopa', 'Hnahthial', 'Tlabung'],
      'Kolasib': ['Kolasib', 'Vairengte', 'Bairabi', 'Thingdawl', 'Bilkhawthlir'],
      'Champhai': ['Champhai', 'Ngopa', 'Khawbung', 'Hmunzawl', 'Khawzawl'],
    },
    'Nagaland': {
      'Kohima': ['Kohima', 'Chakabama', 'Phek', 'Tseminyu', 'Jotsoma'],
      'Dimapur': ['Dimapur', 'Chumukedima', 'Medziphema', 'Dhansiripar', 'Niuland'],
      'Mokokchung': ['Mokokchung', 'Mangkolemba', 'Chungtia', 'Tuli', 'Longsa'],
      'Wokha': ['Wokha', 'Bhandari', 'Chukitong', 'Sanis', 'Sungro'],
      'Mon': ['Mon', 'Aboi', 'Tizit', 'Longching', 'Naginimora'],
    },
    'Arunachal Pradesh': {
      'Itanagar': ['Itanagar', 'Naharlagun', 'Nirjuli', 'Banderdewa', 'Doimukh'],
      'Tawang': ['Tawang', 'Lumla', 'Jang', 'Mukto', 'Thingbu'],
      'Pasighat': ['Pasighat', 'Mebo', 'Bilat', 'Pangin', 'Ruksin'],
      'Bomdila': ['Bomdila', 'Kalaktang', 'Rupa', 'Singchung', 'Thrizino'],
      'Tezu': ['Tezu', 'Namsai', 'Chowkham', 'Lohit', 'Wakro'],
    },
    'Sikkim': {
      'East Sikkim': ['Gangtok', 'Rangpo', 'Ranka', 'Singtam', 'Pakyong'],
      'West Sikkim': ['Geyzing', 'Pelling', 'Yuksom', 'Dentam', 'Soreng'],
      'North Sikkim': ['Mangan', 'Chungthang', 'Lachung', 'Lachen', 'Dzongu'],
      'South Sikkim': ['Namchi', 'Ravangla', 'Jorethang', 'Melli', 'Temi'],
    },
    'Puducherry': {
      'Puducherry': ['Puducherry', 'Oussudu', 'Villianur', 'Ariyankuppam', 'Bahour'],
      'Karaikal': ['Karaikal', 'Tirunallar', 'Nedungadu', 'Kotuchery', 'T.R.Pattinam'],
      'Yanam': ['Yanam', 'Mettakur', 'Yanam Rural'],
      'Mahe': ['Mahe', 'Palloor', 'Pandakkal', 'Chalakara'],
    },
    'Andaman and Nicobar Islands': {
      'South Andaman': ['Port Blair', 'Wandoor', 'Ferrargunj', 'Bamboo Flat', 'Ograbraj'],
      'North and Middle Andaman': ['Mayabunder', 'Rangat', 'Diglipur', 'Kalighat', 'Nimbutala'],
      'Nicobar': ['Car Nicobar', 'Campbell Bay', 'Nancowry', 'Katchal', 'Great Nicobar'],
    },
    'Dadra and Nagar Haveli and Daman and Diu': {
      'Dadra and Nagar Haveli': ['Silvassa', 'Amli', 'Naroli', 'Rakholi', 'Samarvarni'],
      'Daman': ['Daman', 'Nani Daman', 'Moti Daman', 'Kachigam', 'Ringanwada'],
      'Diu': ['Diu', 'Vanakbara', 'Ghoghla', 'Fudam', 'Bucharwada'],
    },
    'Lakshadweep': {
      'Lakshadweep': ['Kavaratti', 'Agatti', 'Minicoy', 'Amini', 'Andrott'],
    },
    'Ladakh': {
      'Leh': ['Leh', 'Nubra', 'Pangong', 'Nyoma', 'Durbuk'],
      'Kargil': ['Kargil', 'Zanskar', 'Drass', 'Sankoo', 'Shakar Chiktan'],
    },
  };

  static List<String> get allStates => stateDistrictCity.keys.toList()..sort();

  static List<String> getDistricts(String state) {
    return stateDistrictCity[state]?.keys.toList() ?? [];
  }

  static List<String> getCities(String state, String district) {
    return stateDistrictCity[state]?[district] ?? [];
  }
}
