import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:agrimore_core/agrimore_core.dart';
import '../../../providers/vendor_provider.dart';
import '../../../app/themes/admin_colors.dart';

class VendorsListScreen extends StatelessWidget {
  const VendorsListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Vendor Management', style: TextStyle(color: Colors.black)),
        backgroundColor: Colors.white,
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.add, color: AdminColors.primary),
            onPressed: () {
              _showAddVendorDialog(context);
            },
          )
        ],
      ),
      body: Consumer<VendorProvider>(
        builder: (context, provider, child) {
          if (provider.isLoading) {
            return const Center(child: CircularProgressIndicator());
          }
          if (provider.error != null) {
            return Center(child: Text(provider.error!));
          }
          if (provider.vendors.isEmpty) {
            return const Center(child: Text('No vendors found.'));
          }

          return ListView.builder(
            itemCount: provider.vendors.length,
            padding: const EdgeInsets.all(16),
            itemBuilder: (context, index) {
              final vendor = provider.vendors[index];
              return Card(
                elevation: 2,
                margin: const EdgeInsets.only(bottom: 12),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                child: ListTile(
                  leading: CircleAvatar(
                    backgroundColor: AdminColors.primary.withOpacity(0.1),
                    child: const Icon(Icons.storefront_rounded, color: AdminColors.primary),
                  ),
                  title: Text(vendor.name, style: const TextStyle(fontWeight: FontWeight.bold)),
                  subtitle: Text('${vendor.phone} • ${vendor.companyName}'),
                  trailing: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                    decoration: BoxDecoration(
                      color: vendor.status == VendorStatus.active ? Colors.green.withOpacity(0.1) : Colors.red.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      vendor.status.name.toUpperCase(),
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: vendor.status == VendorStatus.active ? Colors.green : Colors.red,
                      ),
                    ),
                  ),
                  onTap: () {
                    // Update Status Dialog
                  },
                ),
              );
            },
          );
        },
      ),
    );
  }

  void _showAddVendorDialog(BuildContext context) {
    final nameController = TextEditingController();
    final phoneController = TextEditingController();
    final companyController = TextEditingController();
    
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add New Vendor'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(controller: nameController, decoration: const InputDecoration(labelText: 'Vendor Name')),
            TextField(controller: phoneController, decoration: const InputDecoration(labelText: 'Phone Number')),
            TextField(controller: companyController, decoration: const InputDecoration(labelText: 'Company/Farm Name')),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          ElevatedButton(
            onPressed: () {
              final newVendor = VendorModel(
                id: '', // Generated by firestore in service
                name: nameController.text.trim(),
                phone: phoneController.text.trim(),
                companyName: companyController.text.trim(),
                createdAt: DateTime.now(),
                updatedAt: DateTime.now(),
              );
              context.read<VendorProvider>().addVendor(newVendor);
              Navigator.pop(context);
            },
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }
}
